wp-media/wp-rocket

inc/3rd-party/3rd-party.php
inc/3rd-party/themes/divi.php
inc/3rd-party/yoast-seo.php

Exclude Salvattore script from JS minification

Closes #243

---

inc/common/purge.php

Purge only the cache for the  CPT archive instead of the whole directory

Fixes #249

---

.gitattributes
README.md
min/lib/Minify/HTML.php
wp-rocket.php

Fixed ESI comment tags removed on HTML minify.

---

uninstall.php

Remove cache busting folder when deleting WP Rocket

Fixes #273

---

min/lib/Minify/HTML.php

Preserve Yandex comments during HTML minification

Fixes #272

---

inc/front/cdn.php

Apply CDN to wp_get_attachment_image_src

Closes #271

---

inc/front/cdn.php

Remove &quot; to prevent error with CDN URL

Fixes #289

---

inc/admin/ui/modules/cloudflare.php

Replace dropdown by text field with default value set to the current website domain

Fixes #282

---

inc/front/enqueue.php

Add filters to cache busting and static dynamic resources to excludefiles from the process

Closes #288

---

inc/admin/admin.php
inc/admin/options.php

Export options as JSON instead of gzip

Closes #246

---

inc/3rd-party/hosting/godaddy.php
wp-rocket.php

Fixes #131

---

inc/admin/options.php
inc/admin/ui/enqueue.php
inc/admin/ui/modules/cdn.php
inc/admin/ui/modules/cloudflare.php
inc/admin/ui/modules/optimization.php
inc/common/admin-bar.php
inc/functions/cloudflare.php

UI enhancements on these tabs:
- Static files
- CDN
- Cloudflare
https://github.com/wp-media/wp-rocket/commit/620eb977f1c7b76e907a0e247b5a4a68825bebc9 affects other files, but only UI strings, not other code.

UI enhancements

---

inc/admin/options.php
inc/admin/ui/css/options.css
inc/admin/ui/enqueue.php
inc/admin/ui/modules/advanced.php
inc/admin/ui/modules/basic.php
inc/admin/ui/modules/cdn.php
inc/admin/ui/modules/database.php
inc/admin/ui/modules/optimization.php
inc/admin/ui/modules/preload.php
inc/admin/ui/modules/support.php
inc/admin/ui/modules/tools.php
inc/admin/ui/modules/varnish.php

Finished all the tabs. Left minor string issues (like untranslated “e.g.” in placeholders), but I think this you go as another internal beta.

UX enhancements

---

inc/admin/options.php
inc/admin/ui/enqueue.php
inc/admin/ui/modules/advanced.php
inc/admin/ui/modules/api-key.php
inc/admin/ui/modules/basic.php
inc/admin/ui/modules/cdn.php
inc/admin/ui/modules/database.php
inc/admin/ui/modules/optimization.php
inc/admin/ui/modules/preload.php
inc/admin/ui/modules/tools.php
inc/admin/ui/modules/varnish.php
inc/admin/ui/modules/white-label.php
inc/functions/admin.php

- removed all branding (incl. docs links) from options when WL is enabled
- enhanced license validation panel

White-label support + enhanced license validation panel

---

inc/3rd-party/hosting/wpengine.php

Remove WP Engine CDN auto-activation

Fixes #402 : WP Engine CDN

---

languages/rocket-ru_RU.po

New Russian translation, most visible strings are translated.
Updated: 06.07.2017 09:59

Russian: 63% translated, 401 strings (147 untranslated)

---

inc/functions/htaccess.php

add filter to determine if empty lines should be kept in htaccess

Fixes #157

---

inc/3rd-party/3rd-party.php
inc/3rd-party/plugins/advanced-custom-fields.php

Clear cache when ACF options page is updated

Closes #404

---

inc/admin/options.php
inc/functions/admin.php

Improve settings import to make it work on all browsers

Fixes #464

---

inc/front/minify.php

…Elementor and combine google fonts

Fixes #514

---

wp-rocket.php

https://github.com/wp-media/wp-rocket/blob/branch-2.11/composer.json#L11

GPLv2 or later

---

inc/front/enqueue.php
inc/functions/files.php
inc/functions/formatting.php

* Use filesystem when possible
* Reproduce original tree to file
* Prevent issue with relative paths

Improve remove query strings

---

inc/admin/ui/js/all.js
inc/admin/ui/notices.php
inc/classes/background-processing.php
inc/classes/class-rocket-database-optimization.php
inc/common/purge.php
inc/functions/files.php

* New notices for clear cache and sitemap preload
* Notice classes update

UI Feedbacks first pass

---

inc/admin/options.php
inc/admin/ui/enqueue.php
inc/admin/ui/js/options.js
inc/admin/ui/notices.php
inc/functions/admin.php
inc/functions/cloudflare.php

UI Feedbacks enhancement second pass

---

inc/admin/ui/notices.php

UI Feedbacks third pass

---

inc/functions/i18n.php

If $current_lang is empty we don't want to preserve anything

Fixes #558

---

inc/functions/files.php

Prevent error 500 on some hostings

Fixes #567

---

inc/3rd-party/plugins/wp-offload-s3-assets.php
inc/3rd-party/plugins/wp-offload-s3.php

Prevent fatal error when globals are not set

Fixes #571

---

inc/admin/admin.php

A bit of coding standards fixes and more anonymized data sent to our tracking

Additional data for Mixpanel

---

inc/admin/options.php
inc/admin/ui/modules/basic.php
inc/admin/upgrader.php
inc/deprecated.php
inc/functions/files.php
inc/functions/options.php

Automatically cache SSL pages when needed

Close #701 Remove SSL option

---

inc/functions/formatting.php

rocket_realpath() fix

---

inc/3rd-party/3rd-party.php
inc/3rd-party/plugins/seo/premium-seo-pack.php

Dequeue Premium SEO Pack stylesheet with handle psp-main-style

Fix for #733 - Premium SEO Pack Freezes WP Rocket Settings Page

---

inc/3rd-party/plugins/mobile/amp.php

Prevent error in AMP validator

Fix #738 remove filter inserting critical CSS on AMP pages

---

inc/classes/admin/class-abstract-options.php
inc/classes/admin/class-options-data.php
inc/classes/admin/class-options.php
inc/functions/options.php

First step in the admin code rewrite
- An abstract class
- A class extending the abstract to interact with the Options API (no multisite)
- A class using the previous one to handle the data of one option (interacting with the array)

new Options classes

---

inc/classes/admin/class-options-data.php
inc/functions/options.php

this removes the coupling with the Options class, which was unnecessary

Options_Data class update

---

inc/3rd-party/3rd-party.php
inc/3rd-party/plugins/sumome.php

https://github.com/wp-media/wp-rocket/issues/943

Fix #943 - Added SumoMe compatibility

---

inc/admin/ui/meta-boxes.php
inc/classes/admin/settings/class-page.php

in post editor meta box and data sent to Beacon.

Closes #944 - Updated Async CSS to Optimize CSS Delivery

---

inc/admin/admin.php
inc/admin/options.php
inc/admin/upgrader.php
inc/classes/admin/settings/class-page.php
inc/classes/admin/settings/class-settings.php

By using the zone ID directly we can simplify our connection to Cloudflare API

Closes #940 replace domain field by zone ID field in Cloudflare section

---

inc/3rd-party/plugins/cookies/weepie-cookie-allow.php
inc/front/process.php

The plugin made changes to handle GDPR compatibility, and some customers using it requested an update on WPR compatibility with it to handle the new possible cases.

Update WeePie Cookie Allow compatibility

---

composer.lock
inc/classes/subscriber/Optimization/class-minify-html-subscriber.php
inc/classes/subscriber/class-minify-html-subscriber.php
inc/main.php

Move HTML minification into its own subscriber class

Minify Code Refactor #1: HTML

---

inc/classes/optimization/CSS/class-abstract-css-optimization.php
inc/classes/optimization/CSS/class-combine.php
inc/classes/optimization/CSS/class-minify.php
inc/classes/optimization/CSS/trait-path-rewriter.php
inc/classes/optimization/class-abstract-optimization.php
inc/classes/subscriber/Optimization/class-minify-css-subscriber.php

Structure:
|- Abstract_Optimization
|-- Abstract_CSS_Optimization
|--- Minify
|--- Combine
Minify and Combine share the Path rewriter trait to handle path rewrite in CSS content

Minify Refactor #3: CSS minification/combine

---

inc/classes/optimization/JS/class-abstract-js-optimization.php
inc/classes/optimization/JS/class-combine.php
inc/classes/optimization/JS/class-minify.php
inc/classes/subscriber/Optimization/class-minify-js-subscriber.php

Same structure as the CSS part, but the combine class is more complicated as it's also combining inline and 3rd party scripts except the ones that are excluded

Minify Refactor #4: JavaScript

---

inc/3rd-party/plugins/i18n/wpml.php

Fixes #1039 Tell WooCommerce Multilingual that we are caching

---

inc/3rd-party/3rd-party.php
inc/3rd-party/hosting/o2switch.php
inc/functions/varnish.php
inc/main.php

Add a specific compatibility file for o2switch Varnish setup.
It requires the `O2SWITCH_VARNISH_PURGE_KEY` constant to be defined, which is used by o2switch as `X-VC-Purge-Key` header to authenticate the purge requests.

o2switch Varnish compatibility

---

inc/classes/optimization/JS/class-combine.php

This PR fixes issue #1096 by excluding the optinmonster API JS from being combined.

Excludes Optinmonster Api

---

inc/classes/optimization/CSS/class-combine.php
inc/classes/optimization/CSS/class-minify.php
inc/classes/optimization/JS/class-combine.php
inc/classes/optimization/JS/class-minify.php
inc/classes/optimization/class-cache-dynamic-resource.php
inc/classes/optimization/class-remove-query-string.php
inc/functions/formatting.php

Update the function to work with the most cases possible and update code using it to bail if the path is not ok to prevent issues

Rewrite URL to path conversion function

---

inc/classes/optimization/JS/class-combine.php

Replace the blocklist by an allowlist to make this more scalable

Fix #1138 use an allowlist for inline scripts to combine

---

inc/classes/optimization/CSS/class-combine.php
inc/classes/optimization/CSS/class-minify.php
inc/classes/optimization/JS/class-combine.php
inc/classes/optimization/JS/class-minify.php
inc/classes/optimization/class-remove-query-string.php

Prevent commented scripts/styles from being optimized

Fix #1140 parse HTML without comments for scripts/styles

---

inc/front/process.php

Trim removes too many characters sometimes

Fixes #914 replace trim by preg_replace

---

inc/3rd-party/hosting/pagely.php

This allows you to purge PressCache and also a trigger to let you purge your cache when we purge PressCache

Updating methods to purge PressCache

---

inc/classes/admin/settings/class-beacon.php
inc/classes/admin/settings/class-page.php
inc/classes/class-plugin.php
inc/classes/subscriber/admin/settings/class-beacon-subscriber.php

Take Beacon related code out of the Page Class and to a Beacon and Beacon Subscriber classes.
Update method calls in the Page class to use the new class, and instanciation in the Plugin class.

Move Beacon related code to its own classes

---

inc/admin/upgrader.php
inc/front/process.php
inc/functions/files.php

Introduces a new filter to activate serving the mobile cache version to tablets if required

Fixes #78 Allow serving mobile cache version to tablets

---

inc/classes/busting/class-facebook-pickles.php
inc/classes/busting/class-facebook-sdk.php

Fixes #1243 #1244: Facebook pixel

---

inc/admin/options.php
inc/classes/subscriber/preload/class-preload-subscriber.php
inc/functions/preload.php
inc/main.php

- Preload homepage on activation
- Preload if options have been changed
- Display notice if preload has been triggered from a different page than WP Rocket settings page

Fixes #1248 #1250 #1251 Preload enhancements

---

inc/classes/admin/settings/class-settings.php

Remove protocol from 3rd party URL in Excluded JavaScript Files textarea

Fixes #1189 remove protocol from 3rd party URL for combine JS exclusion

---

inc/common/admin-bar.php
inc/common/purge.php
inc/functions/files.php
inc/functions/i18n.php

Fixes #1207: Disabling WPML via WPML Network Setup causes PHP Fatal Error on Multisite

---

views/settings/page-sections/dashboard.php

use `WP_ROCKET_WHITE_LABEL_ACCOUNT` to hide  the section
Lots of code update for coding standards too

Closes #1029 Hide My Account section with a constant

---

inc/front/cdn.php

If only images is selected as a zone in the CDN settings, rewrite only the images URL and not the other file types

Fixes #521 Rewrite images URL with CDN URL if images zone is selected

---

inc/classes/admin/settings/class-beacon.php

Closes #1301 send current theme with a support request from beacon

---

inc/classes/subscriber/preload/class-partial-preload-subscriber.php

The partial preload could spawn multiple batches with duplicate URLs because of other plugins triggering `rocket_clean_post()` or `rocket_clean_term()` via hooks

Improve partial preload

---

views/settings/fields/cnames.php

Closes #1391 add placeholder to the CNAME field input

---

inc/admin/admin.php
inc/functions/admin.php

Make settings import work again

Fixes #1430 Allow json upload after WP latest security update

---

inc/front/lazyload.php

Before: https://regex101.com/r/U4K5DC/1
After:
Matching the iframe: https://regex101.com/r/mPQivm/1
Matching the `src` attribute: https://regex101.com/r/u8fCWF/1
Matching the Youtube ID: https://regex101.com/r/yjnRhp/1

Fixes #1346: Tags inserted between the <iframe> tag break the iframes lazyload feature

---

inc/common/purge.php

Only delete minify and cache busting files if no specific language is selected

Closes #910 Improve cache deletion with multilingual plugins

---

inc/admin/upgrader.php
inc/functions/admin.php
inc/functions/options.php

- Save the error message(s) encountered in a transient
- Display them in a notice if validation can't be done

Closes #1366 Improve license validation messaging

---

inc/classes/admin/settings/class-page.php
views/settings/fields/checkbox.php

Inform the users the CDN configuration is not required when they use those services

Closes #1024 Display notice on CDN tab if Cloudflare/Sucuri enabled

---

inc/admin/ui/notices.php
inc/functions/htaccess.php

Useful on hosts with Apache but where htaccess is not used

Closes #1429 Add filter to disable htaccess edition

---

inc/admin/ui/meta-boxes.php

Bit of coding standards cleanup too

Closes #1431 Update metabox title

---

wp-rocket.php

**Thank you for wanting to contribute to WP Rocket! Before submitting a pull request, please check that you’ve completed the following steps:**
- Please make sure that there aren’t existing pull requests attempting to address the issue mentioned.
- Check for related issues on the issue tracker.
- Non-trivial changes should be discussed on an issue first.
- Let us know you’re working on the issue.
- Develop in a topic branch, not master.
**Things to add in the pull request to help us:**
- Provide useful pull request description.
- Follow project commit guidelines.
- Write a good description of your PR.
- Link to the Github issue in the description.

Update author URI to use https

---

inc/classes/ServiceProvider/class-third-party-subscribers.php
inc/classes/class-plugin.php
inc/classes/subscriber/third-party/plugins/class-ngg-subscriber.php

Prevent issue with output buffering from NGG with their resource manager after our changes in 3.3.

Fix NGG compatibility with their resource manager

---

inc/classes/ServiceProvider/class-third-party-subscribers.php
inc/classes/class-plugin.php
inc/classes/subscriber/third-party/Themes/class-bridge-subscriber.php

Disable lazyload for background images on Bridge theme

Bridge theme compatibility

---

inc/classes/optimization/JS/class-combine.php

Closes #1621 #1626 #1627 #1668 #1670 #1676

Add new inline JS exclusions

---

inc/classes/optimization/CSS/class-critical-css.php

Exclude CPTs and taxonomies from CPCSS generation

---

inc/admin/ui/notices.php

Add incompatible plugins to the admin notice

---

inc/classes/subscriber/third-party/plugins/ecommerce/class-woocommerce-subscriber.php
inc/functions/i18n.php

Create different transients to cache the empty cart in the different languages

Fixes #1487 WC Empty Cart Cache is incorrect with multilingual plugins

---

inc/classes/ServiceProvider/class-admin-subscribers.php
inc/classes/class-plugin.php
inc/classes/subscriber/third-party/plugins/Optimization/class-hummingbird-subscriber.php
phpcs.xml

Display a notice when one or more options of Hummingbird are active and conflict with WP Rocket active options

Closes #1658 Add a notice for Hummingbird compatibility

---

inc/classes/optimization/JS/class-combine.php

https://www.diffchecker.com/3NSmVd3x#left-2

Add ct_checkjs_ pattern to exclude

---

inc/3rd-party/themes/avada.php

**GitHub issue:** https://github.com/wp-media/wp-rocket/issues/1551
**Related ticket:** https://secure.helpscout.net/conversation/780125419/96833?folderId=2135277

Fixes #1551 - 404 on minified files when using Fusion Patcher

---

inc/classes/optimization/CSS/class-critical-css.php
inc/classes/subscriber/Optimization/class-critical-css-subscriber.php

Also prevent regenerating the CPCSS files on option activation when they already exist

Fixes #1333 Prevent multiple CPCSS generations

---

inc/classes/optimization/CSS/class-combine-google-fonts.php
tests/Fixtures/Optimization/CSS/GoogleFonts/combined-subset.html
tests/Fixtures/Optimization/CSS/GoogleFonts/combined.html
tests/Fixtures/Optimization/CSS/GoogleFonts/original-subset.html
tests/Fixtures/Optimization/CSS/GoogleFonts/original.html
tests/Integration/Optimization/CSS/CombineGoogleFonts/TestOptimize.php
tests/Unit/Optimization/CSS/CombineGoogleFonts/TestOptimize.php

Also add support for the display parameter recently added by Google

Fixes #1713 Prevent 400 error on combined google fonts URL

---

inc/classes/optimization/JS/class-combine.php

- https://www.diffchecker.com/uzqxW9AD
- https://www.diffchecker.com/XcQ48gX4#left-5
- https://www.diffchecker.com/Ie9uRVn8#left-1
- https://www.diffchecker.com/qVVFQb4r#left-2
- https://www.diffchecker.com/RKDzf46A#left-2
- https://www.diffchecker.com/oBZAwVXM#left-2
- https://www.diffchecker.com/4MC9GzLh#left-2
- https://www.diffchecker.com/qGeGu0aa
- https://www.diffchecker.com/KxflQKFJ
- https://www.diffchecker.com/cecgsjWr#left-2
- https://www.diffchecker.com/NIk12oEw#left-2
- https://www.diffchecker.com/5nhQT4di#left-2
- https://www.diffchecker.com/yrvN1Pd0#left-2
- https://www.diffchecker.com/wDvSBV3v#left-2
- https://www.diffchecker.com/Th7XJ0pg#left-2
- https://www.diffchecker.com/RUK8RUVU#left-2
- https://www.diffchecker.com/ijGuWifi#left-2
- …

Auto-exclude 27 new Inline JS patterns

---

inc/classes/optimization/JS/class-combine.php

- https://www.diffchecker.com/EbAuNvHD#left-2
- https://www.diffchecker.com/kzJtyrl7#left-3
- https://www.diffchecker.com/6gmMq8h2#left-2

Add new Inline JS exclusion

---

inc/3rd-party/themes/uncode.php
inc/deprecated/3.3.php

Code is no longer needed since Uncode v2.10

Fixes #1806 Remove old Uncode compatibility code

---

inc/classes/subscriber/Plugin/class-updater-subscriber.php

[Regex test](https://regex101.com/r/sPG54d/2/).

Fixes the update system for alpha/beta versions

---

inc/classes/optimization/JS/class-combine.php

Added exclusions, comments with strings available

JS Exclusions Piotr

---

inc/classes/optimization/JS/class-combine.php

- https://www.diffchecker.com/7qN59gnr#left-2
- https://www.diffchecker.com/leBcendF#left-2
- https://www.diffchecker.com/3uOQ9F27#left-6

Exclude new Inline JS

---

inc/3rd-party/3rd-party.php
inc/3rd-party/themes/impreza.php

This adds support for the impreza theme:
https://themeforest.net/item/impreza-retina-responsive-wordpress-theme/6434280

Add support for the impreza theme

---

inc/3rd-party/plugins/nginx-helper.php
inc/admin/admin.php
inc/admin/ui/meta-boxes.php
inc/admin/ui/notices.php
inc/admin/upgrader.php
inc/classes/ServiceProvider/class-common-subscribers.php
inc/classes/admin/class-logs.php
inc/classes/admin/settings/class-beacon.php
inc/classes/admin/settings/class-page.php
inc/classes/class-plugin.php
inc/classes/class-wp-rocket-requirements-check.php
inc/classes/subscriber/Optimization/class-critical-css-subscriber.php
inc/classes/subscriber/Plugin/class-capabilities-subscriber.php
inc/classes/subscriber/Plugin/class-updater-api-common-subscriber.php
inc/classes/subscriber/admin/Database/class-optimization-subscriber.php
inc/classes/subscriber/admin/Deactivation/class-deactivation-intent-subscriber.php
inc/classes/subscriber/admin/Settings/class-page-subscriber.php
inc/classes/subscriber/preload/class-preload-subscriber.php
inc/classes/subscriber/preload/class-sitemap-preload-subscriber.php
inc/classes/subscriber/third-party/plugins/Optimization/class-hummingbird-subscriber.php
inc/classes/subscriber/third-party/plugins/security/class-sucuri-subscriber.php
inc/common/admin-bar.php
inc/common/purge.php
inc/functions/preload.php

This will give access to the following capabilities:
- rocket_manage_options
- rocket_purge_cache
- rocket_purge_posts
- rocket_purge_terms
- rocket_purge_users
- rocket_purge_opcache
- rocket_purge_cloudflare_cache
- rocket_purge_sucuri_cache
- rocket_preload_cache
- rocket_regenerate_critical_css
Each capability can be assigned to a role using custom code, or using the User Role Editor plugin

Add custom capabilities to allow easier configuration to the plugin actions

---

inc/classes/preload/class-full-process.php
inc/classes/preload/class-partial-process.php
inc/classes/subscriber/preload/class-partial-preload-subscriber.php

Also fix an issue when checking if an URL is already cached.

Closes #1577: Query strings and search urls not preloaded via sitemap

---

tests/Unit/CDN/TestRewrite.php
tests/Unit/CDN/TestRewriteCSSProperties.php
tests/Unit/CDN/TestRewriteURL.php
tests/Unit/Functions/Options/TestExcludeDeferJS.php
tests/Unit/Optimization/CSS/Combine/TestInsertCombinedCSS.php
tests/Unit/Optimization/CSS/CombineGoogleFonts/TestOptimize.php
tests/Unit/TestCase.php

This class contains `setUp()` and `tearDown()`, which are common to all our tests. Tests will then extend the class, and extend the methods if needed.

Improvement new TestCase class for unit tests

---

inc/admin/ui/notices.php
inc/classes/optimization/CSS/class-critical-css-generation.php
inc/classes/preload/class-full-process.php
inc/classes/subscriber/Optimization/class-critical-css-subscriber.php
inc/classes/subscriber/preload/class-preload-subscriber.php

Added a date & time after some messages related to: PreLoad, Clear Cache, CPCSS

Fixes #1867 - Append date and time to admin notices

---

inc/classes/subscriber/class-google-tracking-cache-busting-subscriber.php

Fixed: Allowed both Google Tracking and GTM tracking code

Allowed both Google Tracking and GTM

---

inc/classes/subscriber/third-party/plugins/security/class-sucuri-subscriber.php

Added filter to adjust the cURL timeout for Sucuri add-on

#1835 Added filter to adjust cURL timeout for Sucuri

---

inc/classes/ServiceProvider/class-third-party-subscribers.php
inc/classes/class-plugin.php
inc/classes/subscriber/third-party/plugins/ecommerce/class-bigcommerce-subscriber.php

Auto-Exclude BigCommerce pages from cache

Closes #1679 BigCommerce compatibility

---

inc/classes/subscriber/Media/class-webp-subscriber.php
tests/Fixtures/Subscriber/Media/WebpSubscriber/html/expected.html
tests/Fixtures/Subscriber/Media/WebpSubscriber/html/matching.html
tests/Fixtures/Subscriber/Media/WebpSubscriber/html/not-matching-attributes.html
tests/Fixtures/Subscriber/Media/WebpSubscriber/html/not-matching-file-extensions.html
tests/Fixtures/Subscriber/Media/WebpSubscriber/html/not-matching-with-empty-sources.html
tests/Unit/Subscriber/Media/WebpSubscriber/TestConvertToWebp.php
tests/Unit/Subscriber/Media/WebpSubscriber/TestMaybeDisableSettingField.php
tests/Unit/Subscriber/Media/WebpSubscriber/TestMaybeDisableWebpCache.php
tests/Unit/Subscriber/Media/WebpSubscriber/TestSyncWebpCacheWithThirdPartyPlugins.php
tests/Unit/Subscriber/Media/WebpSubscriber/TestWebpSectionDescription.php
tests/Unit/TestCase.php

Covered:
- `WP_Rocket\Subscriber\Media\Webp_Subscriber`

Unit tests for webp

---

inc/classes/class-wp-rocket-requirements-check.php
wp-rocket.php

* Use default cap for `manage_options`
* Fix various CS
* Check for DB values before constants in `add_own_ua()` method

WPR Requirements checks update

---

inc/classes/subscriber/Media/class-webp-subscriber.php
inc/common/purge.php

Added a filter to the args of the request preloading the home page after the cache is purged manually. Then used it to add the required headers.

Preload webp cache after purge

---

inc/admin/admin.php
inc/classes/subscriber/Plugin/class-capabilities-subscriber.php
inc/main.php

- Add/Remove capabilities on plugin's activation/deactivation

Capabilities setup

---

tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestIsConvertingToWebp.php
tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestIsServingWebp.php
tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestIsServingWebpCompatibleWithCdn.php
tests/Unit/ThirdParty/Plugins/Images/Webp/EwwwSubscriber/TestMaybeRemoveImagesFromCdnDropdown.php
tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestGetBasename.php
tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestIsConvertingToWebp.php
tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestIsServingWebp.php
tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestIsServingWebpCompatibleWithCdn.php
tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestLoadHooks.php
tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnNetworkOptionAdd.php
tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnNetworkOptionDelete.php
tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnNetworkOptionUpdate.php
tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnOptionAdd.php
tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnOptionDelete.php
tests/Unit/ThirdParty/Plugins/Images/Webp/ImagifySubscriber/TestSyncOnOptionUpdate.php

Unit tests for class Imagify_Subscriber

---

inc/admin/upgrader.php
inc/functions/options.php
tests/Unit/Admin/Upgrader/testRocketUpgrader.php
tests/Unit/Cache/TestPurgeExpiredFiles.php
wp-rocket.php

Delete the file once the licence is validated, on first installation and on update.

Delete licence-data.php file once the licence is validated

---

inc/admin/ui/notices.php
inc/admin/upgrader.php
inc/common/purge.php

Added admin notices for OPCache clearing
OPCache clearing - Issue demo - https://jmp.sh/JZiRHTc
Based on:

Admin notice for OPCache clearing

---

inc/classes/admin/settings/class-beacon.php
inc/classes/admin/settings/class-page.php

Update Cloudflare "Find Your API Key" doc link 
EN: https://docs.wp-rocket.me/article/18-using-wp-rocket-with-cloudflare#add-on
FR: https://fr.docs.wp-rocket.me/article/247-utiliser-wp-rocket-avec-cloudflare#add-on

Fix #2017 - Update Cloudflare "Find Your API Key" doc link

---

inc/3rd-party/3rd-party.php
inc/3rd-party/hosting/litespeed.php
inc/functions/litespeed.php
inc/main.php

Add LiteSpeed compatibility using X-LiteSpeed-Purge header
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:cache:developer_guide:response_headers

Fixes #73: LiteSpeed compatibility

---

inc/common/cloudflare-flexible-ssl.php
inc/functions/cloudflare.php
inc/main.php

Fix for Cloudflare Flexible SSL redirect loop

Fix #1922 Cloudflare flexible SSL redirect loop

---

inc/classes/optimization/JS/class-combine.php

Related tickets:
* https://secure.helpscout.net/conversation/968426648/124873/
* https://secure.helpscout.net/conversation/975180861/125887/
* https://secure.helpscout.net/conversation/974899436/125853/
* https://secure.helpscout.net/conversation/972589926/125539/

Exclude inline JavaScript - /cache/min folder size

---

inc/functions/cloudflare.php
wp-rocket.php

Updated version no.
Fixed undefined notice from Cloudflare

Fixes #2058 3.4.1-alpha2 - Wrong version number and PHP notices

---

inc/functions/cloudflare.php
wp-rocket.php

Cloudflare zone validation based on `/zones/ID_ZONE`
Increased version no. 3.4.1-alpha3

Cloudflare zone validation with zone_id and increased version no to 3.4.1-alpha3

---

inc/classes/CDN/CDN.php
tests/Fixtures/CDN/original.html
tests/Fixtures/CDN/rewrite.html
tests/Fixtures/CDN/srcset/rewrite.html

- Prevent double rewrite of srcset sources with relative URL
- Rewrite relative URL in subfolders
- Update unit tests
RegEx test: https://regex101.com/r/uOgjun/13

Fixes #2041 Prevent double rewrite of srcset with relative URL

---

inc/functions/cloudflare.php

Fix Cloudflare domain validation with strpos instead of strict comparison

Fix #2077 Cloudflare domain validation

---

inc/classes/admin/settings/class-settings.php
inc/deprecated/3.4.php
inc/functions/cloudflare.php
wp-rocket.php

Fixed Cloudflare slow issues - calls to API validation on each page
Fixed: Cloudflare fatal error with missing function rocket_is_api_keys_valid_cloudflare
Increased version no.

Cloudflare: slow issues & fatal error

---

inc/admin/admin.php

Fixed mime_types on import settings on a multisite
Based on 3.4.2 doc

Fixed #1765 Import Settings on a multisite, fixed mime_type

---

inc/classes/subscriber/third-party/plugins/class-mobile-subscriber.php

Detect JetPack mobile theme and activate separate mobile cache option to prevent conflicts
Based on v3.4.2 minor version

Fix #1661 - Detect Jetpack mobile theme

---

inc/classes/subscriber/third-party/plugins/class-smush-subscriber.php

Fixed Smush LazyLoad option set to 0 when Smush plugin is activated

Fixed Smush update lazyload option at activation

---

inc/classes/subscriber/Tools/class-detect-missing-tags-subscriber.php
tests/Unit/Subscriber/Tools/TestDetectMissingTags.php

Closing tags - removed transient expiration time

Closing tags - removed transient expiration time

---

inc/classes/subscriber/Tools/class-detect-missing-tags-subscriber.php
tests/Unit/Subscriber/Tools/TestDetectMissingTags.php

Do not report missing tags when page http response code is not 200

Do not report missing tags when the http response is not 200

---

inc/classes/Cache/class-expired-cache-purge.php
tests/Unit/Cache/TestPurgeExpiredFiles.php

When the filter `do_rocket_generate_caching_files` is set to `false`, do not delete cache files (but still trigger surrounding hooks). #2050

Closes #2050: Automatic Cache Clearing - Do not attempt to clear cache files when do_rocket_generate_caching_files is false

---

inc/3rd-party/hosting/godaddy.php

Fixes #2087 Remove rewrite rules on GoDaddy Managed Hosting

---

inc/classes/CDN/CDN.php
tests/Fixtures/CDN/original.html
tests/Fixtures/CDN/rewrite.html
tests/Fixtures/CDN/srcset/rewrite.html

Use a more specific characters class to match against the file extension. Only match for alphanumeric characters.

Fixes #2132 Incorrect matching for CDN rewrite

---

inc/classes/optimization/CSS/trait-path-rewriter.php

Add target path and source path in rocket_css_content filter
Based on v3.4.3 doc

Fix #2127 - Add target path and source path in rocket_css_content filter

---

inc/functions/cloudflare.php

Cleaning Cloudflare cache when a post cache is cleaned needed also the home URL and the feeds URLs

Added Home and Feed URLs to Cloudflare clean cache API call

---

inc/admin/ui/notices.php

- Cache Enabler (Fixes #2152)
- Swift Performance Lite & Pro
- Add Expires Header
- Merge + Minify + Refresh

Add new plugins to the incompatibility list

---

inc/classes/subscriber/preload/class-partial-preload-subscriber.php

Partial preloading is not working after cache lifespan expires based on trailing /

Fix #2142 - Partial Preloading is not working after cache lifespan expires

---

inc/classes/optimization/class-cache-dynamic-resource.php

Fixes PHP 7.4 notice 
```
Notice: Trying to access array offset on value of type null in /public/wp-content/plugins/wp-rocket/inc/classes/optimization/class-cache-dynamic-resource.php on line 170
```
Reference Issue #2185

Fix #2185 - PHP 7.4 notice - Trying to access array offset on value of type null, in class-cache-dynamic-resource.php

---

inc/classes/logger/class-logger.php
inc/front/process.php
uninstall.php
wp-rocket.php

Removes the changes from PR #2120 for branch 3.4.4
PR #2120 it is prepared and tested for v3.5 and should not be included in v3.4.4 release.

Removed changes from PR #2120 from branch 3.4.4

---

inc/classes/optimization/JS/class-combine.php

Add inline JavaScript exclusions

Add inline JavaScript exclusions

---

inc/classes/optimization/JS/class-combine.php

In order to prevent a cache dir size issue 
Ticket: https://secure.helpscout.net/conversation/1045836098/139123?folderId=1213662

Exclude pw_brand_product_list from combined JS

---

inc/classes/optimization/JS/class-combine.php

From this ticket: https://secure.helpscout.net/conversation/1067472348/143170?folderId=1213662

Exclude tarteaucitron scripts from being combined

---

inc/classes/optimization/JS/class-combine.php

**Related ticket:** https://secure.helpscout.net/conversation/1076430628/144885?folderId=377611#thread-3051396215

Exclude inline JavaScript

---

composer.lock
tests/Integration/FilesystemTestCase.php
tests/Integration/inc/classes/Cache/Expired_Cache_Purge/purgeExpiredFiles.php
tests/Unit/FilesystemTestCase.php
tests/Unit/inc/classes/Cache/Expired_Cache_Purge/purgeExpiredFiles.php

1. Fixes the classname for the abstract integration `FilesystemTestCase`. Doh (my mistake).
2. Adds more files into the baseline virtual filesystem structure. Credit @Tabrisrp.
3. Improves the `Expired_Cache_Purge::purge_expired_files()` tests.

Fixes and improves the Virtual Filesystem Test Suites.

---

composer.json
composer.lock

- Removed dependency on my fork of wp-background-processing
- Copied fork to wp-media/background-processing
- Published the new repository on packagist
- Update composer.json with the new source

Update Background Processing dependency

---

inc/classes/admin/settings/class-beacon.php
inc/classes/subscriber/CDN/RocketCDN/AdminPageSubscriber.php
tests/Integration/Subscriber/CDN/RocketCDN/AdminPageSubscriber/rocketcdnField.php
tests/Unit/Subscriber/CDN/RocketCDN/AdminPageSubscriber/rocketcdnField.php
views/settings/fields/rocket-cdn.php

Add documentation URL & ID from Beacon for RocketCDN, french version coming later

Add documentation data for RocketCDN

---

tests/Fixtures/inc/functions/getRocketSamplePermalink.php
tests/Integration/inc/functions/getRocketSamplePermalink.php
tests/Unit/bootstrap.php
tests/Unit/inc/functions/getRocketSamplePermalink.php

Adds unit and integration tests for `get_rocket_sample_permalink()`.
QA is not needed for this as source code was not changed. Tests only.

Tests: Adds tests for get_rocket_sample_permalink()

---

inc/functions/files.php
tests/Fixtures/inc/functions/rocketIsStream.php
tests/Fixtures/inc/functions/rocketMkdirP.php
tests/Integration/inc/classes/subscriber/Optimization/class-critical-css-subscriber/generateCriticalCssOnActivation.php
tests/Integration/inc/functions/rocketMkdirP.php
tests/Unit/inc/functions/rocketIsStream.php
tests/Unit/inc/functions/rocketMkdirP.php

This makes the function compatible with VfsStream (and other stream URLs)

Make rocket_mkdir_p compatible with streams

---

inc/functions/i18n.php
tests/Fixtures/i18n/PLL_Frontend.php
tests/Fixtures/i18n/pluginsData.php
tests/Fixtures/inc/functions/getRocketI18nHomeUrl.php
tests/Fixtures/inc/functions/getRocketI18nToPreserve.php
tests/Integration/inc/functions/getRocketI18nHomeUrl.php
tests/Integration/inc/functions/getRocketI18nToPreserve.php
tests/Integration/inc/functions/getRocketI18nUri.php
tests/Unit/inc/functions/getRocketI18nHomeUrl.php
tests/Unit/inc/functions/getRocketI18nToPreserve.php

Adds unit and integration tests for:
- `get_rocket_i18n_to_preserve()`
- `get_rocket_i18n_home_url()`
This PR is needed for PR #2510 and others.
QA is not needed for this PR.

Tests: adds tests for get_rocket_i18n_home_url() and get_rocket_i18n_to_preserve()

---

inc/common/purge.php
tests/Fixtures/WP_Theme.php
tests/Fixtures/inc/common/rocketCleanCacheThemeUpdate.php
tests/Integration/FilesystemTestCase.php
tests/Integration/inc/common/rocketCleanCacheThemeUpdate.php
tests/Unit/inc/common/TestCase.php
tests/Unit/inc/common/rocketCleanCacheThemeUpdate.php
tests/Unit/inc/common/rocketCleanPostCacheOnSlugChange.php
tests/Unit/inc/common/rocketWidgetUpdateCallback.php

Unit and integration tests for `rocket_clean_cache_theme_update()`.

Tests: for rocket_clean_cache_theme_update().

---

tests/Fixtures/inc/functions/isRocketGenerateCachingMobileFiles.php
tests/Integration/inc/functions/isRocketGenerateCachingMobileFiles.php
tests/Unit/inc/functions/isRocketGenerateCachingMobileFiles.php

Adds tests for `is_rocket_generate_caching_mobile_files()`.

Tests: is_rocket_generate_caching_mobile_files()

---

inc/functions/files.php
tests/Fixtures/inc/functions/rocketPutContent.php
tests/Integration/inc/functions/rocketPutContent.php
tests/Unit/inc/functions/rocketPutContent.php

Adds unit and integration tests for `rocket_put_content()`.
No QA needed as this PR does not change the source code.

Tests: rocket_put_content()

---

inc/Engine/Optimization/Minify/JS/Combine.php

Ticket: https://secure.helpscout.net/conversation/1142279920/159445/

Exclude inline JavaScript to prevent the cache dir size issue

---

inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php

Adding nonces related to the Dokan

Adding two nonces to the array

---

inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php

Ticket: https://secure.helpscout.net/conversation/1160419126/164072/
I have already confirmed this is working on the customer's website.

Exclude Ultimate Addons for Beaver Builder nonce action.

---

.travis.yml

...and `true` is a better `return 0`

Fix unpredictable caching on TravisCI

---

inc/main.php

Early loads the `inc/functions/files.php` to enable `rocket_direct_filesystem()` to be injected into objects at instantiation.

Early loads filesystem functions to enable dependency injection

---

views/settings/page-sections/database.php

https://github.com/wp-media/wp-rocket/issues/2154
Based on @GeekPress reply in here the button text was changed into `Save Settings and Optimize`
https://github.com/wp-media/wp-rocket/issues/2154#issuecomment-629131848

Closes #2154 improve optimize button text on db tab

---

inc/Engine/CDN/RocketCDN/AdminPageSubscriber.php
inc/Engine/CDN/RocketCDN/NoticesSubscriber.php
tests/Fixtures/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/addSubscriptionModal.php
tests/Fixtures/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/displayManageSubscription.php
tests/Fixtures/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/displayRocketcdnStatus.php
tests/Fixtures/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/rocketcdnField.php
tests/Fixtures/inc/Engine/CDN/RocketCDN/NoticesSubscriber/addDismissScript.php
tests/Fixtures/inc/Engine/CDN/RocketCDN/NoticesSubscriber/displayRocketcdnCta.php
tests/Fixtures/inc/Engine/CDN/RocketCDN/NoticesSubscriber/promoteRocketcdnNotice.php
tests/Integration/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/addSubscriptionModal.php
tests/Integration/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/displayManageSubscription.php
tests/Integration/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/displayRocketcdnStatus.php
tests/Integration/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/rocketcdnField.php
tests/Integration/inc/Engine/CDN/RocketCDN/NoticesSubscriber/addDismissScript.php
tests/Integration/inc/Engine/CDN/RocketCDN/NoticesSubscriber/dismissNotice.php
tests/Integration/inc/Engine/CDN/RocketCDN/NoticesSubscriber/displayRocketcdnCta.php
tests/Integration/inc/Engine/CDN/RocketCDN/NoticesSubscriber/promoteRocketcdnNotice.php
tests/Integration/inc/Engine/CDN/RocketCDN/NoticesSubscriber/purgeCacheNotice.php
tests/Integration/inc/Engine/CDN/RocketCDN/NoticesSubscriber/toggleCta.php
tests/StubTrait.php
tests/Unit/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/addSubscriptionModal.php
tests/Unit/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/displayManageSubscription.php
tests/Unit/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/displayRocketcdnStatus.php
tests/Unit/inc/Engine/CDN/RocketCDN/AdminPageSubscriber/rocketcdnField.php
tests/Unit/inc/Engine/CDN/RocketCDN/NoticesSubscriber/addDismissScript.php
tests/Unit/inc/Engine/CDN/RocketCDN/NoticesSubscriber/displayRocketcdnCta.php
tests/Unit/inc/Engine/CDN/RocketCDN/NoticesSubscriber/promoteRocketcdnNotice.php

Closes #2566 Hide RocketCDN when white label is enabled

---

inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php

Added nonce action related to the Konte theme.

Added nonce

---

inc/functions/files.php
tests/Fixtures/inc/functions/rocketFindWpconfigPath.php
tests/Integration/inc/functions/rocketFindWpconfigPath.php
tests/Unit/inc/functions/rocketFindWpconfigPath.php

Add Unit and Integration tests for `rocket_find_wpconfig_path` method which locates in `inc/functions/files.php`

Add tests for rocket_find_wpconfig_path function

---

inc/Engine/Admin/Beacon/Beacon.php
tests/Fixtures/inc/Engine/Admin/Beacon/Beacon/insertScript.php

- Add `Unavailable` index to the array
- Update fixtures

Prevent php notice: Unavailable index in Beacon

---

inc/Engine/Admin/Beacon/Beacon.php
inc/Engine/CriticalPath/Admin/Post.php
inc/Engine/CriticalPath/Admin/Settings.php
tests/Fixtures/inc/Engine/CriticalPath/Admin/Post/cpcssActions.php
tests/Fixtures/inc/Engine/CriticalPath/Admin/Post/cpcssSection.php
tests/Fixtures/inc/Engine/CriticalPath/Admin/Settings/displayCpcssMobileSection.php
views/cpcss/activate-cpcss-mobile.php
views/cpcss/metabox/generate.php

French ID: 5d5abada0428634552d85bff
English ID: 5d52144c0428631e94f94ae2c
```
'async'                      => [
'en' => [
'id'  => '5d52144c0428631e94f94ae2',
'url' => 'https://docs.wp-rocket.me/article/1266-optimize-css-delivery/?utm_source=wp_plugin&utm_medium=wp_rocket',
],
'fr' => [
'id'  => '5d5abada0428634552d85bff',
'url' => 'https://fr.​docs.​wp-rocket.​me/article/1268-optimiser-le-chargement-du-css/?utm_source=wp_plugin&utm_medium=wp_rocket',
],
],
```

Revisited CPCSS beacon id and URLs

---

inc/Engine/CriticalPath/CriticalCSSSubscriber.php

Early bailout if no desktop message from CPCSS in the transient

Fixed unwanted notice for mobile CPCSS ( early bailout if no desktop message )

---

inc/functions/htaccess.php
tests/Fixtures/inc/functions/rocketGetCompressedAssets.php
tests/Unit/inc/functions/rocketGetCompressedAssetsRules.php

Fixes #2767 update compressed rules & tests

---

inc/Engine/Media/LazyloadSubscriber.php
tests/Fixtures/inc/Engine/Media/LazyloadSubscriber/insertLazyloadScript.php
tests/Integration/inc/Engine/Media/LazyloadSubscriber/insertLazyloadScript.php
tests/StubTrait.php
tests/Unit/inc/Engine/Media/LazyloadSubscriber/insertLazyloadScript.php

Closes #2535 
Stop loading lazyload assets on search page.

Remove lazyload from search page

---

inc/Engine/CriticalPath/CriticalCSSSubscriber.php

Add insert load CSS in head when fallback CSS is used

Fallback CSS insert load CSS code in head

---

inc/Engine/Optimization/Minify/JS/Combine.php

https://www.diffchecker.com/T0OWklU5
https://www.diffchecker.com/tnb0cqPJ
https://www.diffchecker.com/nXuEVYpQ

Added excluded inline JS

---

inc/Engine/Optimization/Minify/JS/Combine.php

captcha-hash
mapdata={
https://www.diffchecker.com/DrDSIhOT#left-4

Excluded dynamic JS

---

inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php

Ticket: https://secure.helpscout.net/conversation/1252699151/186413/#thread-3591428397
GitHub issue: #2318 
Related Slack conversation: https://wp-media.slack.com/archives/C43T1AYMQ/p1598275277020100

Closes #2318 Add i18n.min.js to the $excluded_files array

---

wp-rocket.php

Steps before going production for version 3.7

Before production v3.7

---

inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php

Related to **WP User Frontend Pro**: 
https://secure.helpscout.net/conversation/1246080211/184796?folderId=2683093

Adding one nonce to the array

---

inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php

Related ticket:
- https://secure.helpscout.net/conversation/1252699151/186413/#thread-3591428397

Exclude Simplybook's widget from JS minification/combination

---

inc/Engine/Optimization/DelayJS/HTML.php

Fix Delay JS regex issue with large page html

---

inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php

Related ticket: https://secure.helpscout.net/conversation/1267575517/190733/

Exclude static.botsrv.com from JavaScript minification/combination

---

inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php

**Related ticket:** https://secure.helpscout.net/conversation/1261807186/189299?folderId=2135277

Exclude Everest Forms nonce actions

---

wp-rocket.php

Before 3.7.1.1 deployment

---

inc/Engine/Optimization/Minify/JS/Combine.php

Add **n2jQuery** to the Excluded Inline JS scripts
Tickets: 
- https://secure.helpscout.net/conversation/1289046182/196681/
- https://secure.helpscout.net/conversation/1291250896/197240/
- https://secure.helpscout.net/conversation/1287335959/196242/

Prevent issue with Smart Slider 3

---

inc/Engine/Optimization/Minify/JS/Combine.php

Tickets:
* https://secure.helpscout.net/conversation/1282483170/194880/
* https://secure.helpscout.net/conversation/1291397946/197286/

Add exclusions to avoid the cache dir size issue

---

inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php
inc/functions/options.php
tests/Integration/inc/functions/getRocketExcludeDeferJs.php
tests/Unit/inc/functions/getRocketExcludeDeferJS.php

Exclude jQuery added from:
https://code.jquery.com/jquery/
**RegEx:** https://regex101.com/r/QMXIUi/1
**Ticket:** https://secure.helpscout.net/conversation/1291100148/197185

Exclude jQuery from code.jquery.js from being deferred

---

inc/Engine/License/API/User.php
inc/Engine/License/ServiceProvider.php
tests/Fixtures/inc/Engine/License/API/User/getCreationDate.php
tests/Fixtures/inc/Engine/License/API/User/getLicenseExpiration.php
tests/Fixtures/inc/Engine/License/API/User/getLicenseType.php
tests/Fixtures/inc/Engine/License/API/User/getUpgradeInfiniteUrl.php
tests/Fixtures/inc/Engine/License/API/User/getUpgradePlusUrl.php
tests/Fixtures/inc/Engine/License/API/User/isAutoRenew.php
tests/Fixtures/inc/Engine/License/API/User/isLicenseExpired.php
tests/Unit/inc/Engine/License/API/User/getCreationDate.php
tests/Unit/inc/Engine/License/API/User/getLicenseExpiration.php
tests/Unit/inc/Engine/License/API/User/getLicenseType.php
tests/Unit/inc/Engine/License/API/User/getUpgradeInfiniteUrl.php
tests/Unit/inc/Engine/License/API/User/getUpgradePlusUrl.php
tests/Unit/inc/Engine/License/API/User/isAutoRenew.php
tests/Unit/inc/Engine/License/API/User/isLicenseExpired.php

This classes provides getter methods to get specific data from the user API, providing guard clauses in case some data is not defined.
- `get_license_type()`: Gets the user license type, based on a numerical value
- `get_license_expiration()`: Gets the user license expiration timestamp
- `is_license_expired()`: Checks if the user license is expired
- `get_creation_date()`: Gets the user license creation date
- `is_auto_renew()`: Checks if auto-renew is enabled for this user license
- `get_upgrade_plus_url()`: Gets the URL to upgrade to plus
- `get_upgrade_infinite_url()`: Gets the URL to upgrade to infinite

User class to manage user data access

---

inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php

**Related ticket:** https://secure.helpscout.net/conversation/1307846560/201997?folderId=2135277

Exclude Leadboxes script

---

inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php

Related ticket: https://secure.helpscout.net/conversation/1305007706/201092?folderId=2135277

Add more actions in the get_nonce_actions() method for compatibility

---

inc/Engine/Optimization/Minify/JS/Combine.php

Tickets:
* https://secure.helpscout.net/conversation/1309259172/202443/
* https://secure.helpscout.net/conversation/1282606874/194949
* https://secure.helpscout.net/conversation/1308648194/202283/
* https://secure.helpscout.net/conversation/1290987139/197151/

Update inline JS exlusions

---

inc/Engine/Optimization/Minify/JS/Combine.php

Related ticket: https://secure.helpscout.net/conversation/1310855187/202854/

Add new inline JS exclusion from combine JS

---

inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php

Related ticket: https://secure.helpscout.net/conversation/1321017203/205983?folderId=2135277

Add nonce action related to Custom Bookly form

---

inc/Engine/Optimization/Minify/JS/Combine.php

**Related tickets:**
https://secure.helpscout.net/conversation/1316541586/204567/
https://secure.helpscout.net/conversation/1320301984/205762/
https://secure.helpscout.net/conversation/1326377084/208000?folderId=2135277

Exclude inline JavaScript keywords

---

.travis.yml
composer.json
wp-rocket.php

Closes #3247 
Update minimum supported PHP version to 7.0.

Closes #3247 Update minimum PHP version to 7.0

---

inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php
inc/functions/options.php
tests/Integration/inc/functions/getRocketExcludeDeferJs.php
tests/Unit/inc/functions/getRocketExcludeDeferJS.php

**Related ticket:** https://secure.helpscout.net/conversation/1336047074/211299/#thread-3865491654

Exclude Civic Computing Cookie JS file from deferring/combination

---

inc/classes/Buffer/class-cache.php
inc/classes/traits/trait-memoize.php

php8 compatibility

---

inc/Engine/Optimization/AbstractOptimization.php
inc/Engine/Optimization/GoogleFonts/CombineV2.php

Epic #3264 - Part 1 of 4
Creates a new CombineV2 class to handle combining API v2 webfont links.

Google Fonts API Enhancement, Part 1 of 4 - New Class

---

.github/k8s_ingress.yaml
.github/workflows/delete-test-wp.yml
.github/workflows/delete_test_wp.yml
.github/workflows/deploy_test_wp.yml

**Thank you for wanting to contribute to WP Rocket! Before submitting a pull request, please check that you’ve completed the following steps:**
- Please make sure that there aren’t existing pull requests attempting to address the issue mentioned.
- Check for related issues on the issue tracker.
- Non-trivial changes should be discussed on an issue first.
- Let us know you’re working on the issue.
- Develop in a topic branch, not master.
**Things to add in the pull request to help us:**
- Provide useful pull request description.
- Follow project commit guidelines.
- Write a good description of your PR.
- Link to the Github issue in the description.

Add auto-deploy of test WP instances

---

inc/Engine/Optimization/Minify/JS/Combine.php

Related tickets:
https://secure.helpscout.net/conversation/1334449836/210792
https://secure.helpscout.net/conversation/1334704859/210858

Add new inline exclusions from combine JS

---

inc/functions/api.php

Siteground new staging domain is .`sg-host.com` per 
https://secure.helpscout.net/conversation/1336598662/211515/

Adding new staging site .sg host.com

---

.github/workflows/deploy.yml

**Thank you for wanting to contribute to WP Rocket! Before submitting a pull request, please check that you’ve completed the following steps:**
- Please make sure that there aren’t existing pull requests attempting to address the issue mentioned.
- Check for related issues on the issue tracker.
- Non-trivial changes should be discussed on an issue first.
- Let us know you’re working on the issue.
- Develop in a topic branch, not master.
**Things to add in the pull request to help us:**
- Provide useful pull request description.
- Follow project commit guidelines.
- Write a good description of your PR.
- Link to the Github issue in the description.

Create deploy.yml to call Ansible AWX

---

inc/Engine/Optimization/Minify/JS/Combine.php

Related tickets:
* https://secure.helpscout.net/conversation/1325060488/207513/
* https://secure.helpscout.net/conversation/1329019282/209010?folderId=273766
* https://secure.helpscout.net/conversation/1346311838/215035?folderId=2135277

Update the inline JavaScript exclusions

---

inc/Engine/Optimization/Minify/JS/Combine.php

Related tickets:
* https://secure.helpscout.net/conversation/1355554806/219388
* https://secure.helpscout.net/conversation/1357544489/220101

Update inline JavaScript exclusions

---

wp-rocket.php

3.8.1 pre-release
