inc/3rd-party/3rd-party.php
inc/3rd-party/wp-retina-2x.php
inc/front/plugin-compatibility.php

Move WP Retina code to 3rd party and improve resilience

Closes #264

---

inc/front/cdn.php
inc/front/enqueue.php

Prevent a JS file from being loaded twice when Remove query strings + defer JS + CDN are active

Fixes #292

---

inc/3rd-party/3rd-party.php
inc/3rd-party/plugins/sf-move-login.php
inc/admin/plugin-compatibility.php
inc/functions/plugins.php

Update compatibility with SF Move Login.
No longer exclude the URLs for version 2.4 and above since it's using DONOTCACHEPAGE constant.

Fixes #286

---

inc/3rd-party/3rd-party.php
inc/3rd-party/page-builder/elementor.php

The Elementor page builder generated pages don't work with WP Rocket (Minify mode activated). 
https://elementor.com/
There is a free and pro version.
I had to exclude every asset files like:
http://domain/wp-content/plugins/elementor/assets/*

Elementor page builder compatibility file

---

inc/admin/ui/modules/support.php

Since the example content of our form gets translated into all the languages, people rightfully assume they can send a message in the language they see being used in the form.
That had led to us receiving support requests in Dutch, Chinese, and other languages we do not speak. ;)
This update extends the description of the support form to mention the languages currently spoken across our support team.

Minor string update: specified support languages

---

inc/front/process.php

Footprint appearing for non-HTML pages in Gzipped cached file

Closes #483

---

inc/admin/ui/modules/cdn.php

@Tabrisrp We don’t wants ampersands in paragraphs text as shortcut for
“and”s, my preciousss. It must run UI strings by an editor, or we shall
curssse it! ;)

Minor string update

---

inc/deprecated.php
inc/front/async-css.php
inc/front/cdn.php
inc/front/enqueue.php
inc/front/lazyload.php
inc/front/minify.php
inc/front/process.php
inc/functions/cdn.php

Common constant to prevent applying WP Rocket optimization when the page is not cached. Previously some things like lazyload and parts of CDN were still applied.

Introduce DONOTROCKETOPTIMIZE constant

---

inc/functions/files.php

Allow to filter the wp config filename, especially useful when in composer installation.

Filter the wp-config filename

---

inc/classes/class-rocket-critical-css.php
inc/classes/class-rocket-database-optimization.php
inc/functions/bots.php

This is caused by the use of an outdated version of the WPBP library in other plugins, loaded before WP Rocket.
To prevent the fatal, wrap the calls to `cancel_process()` in a method exists.

Fix #646 fatal error undefined method cancel_process()

---

inc/admin/options.php
inc/admin/ui/modules/preload.php

Remove the dropdown field, keep the option as an hidden field.
The value output can be filtered using our `pre_rocket_get_option` filter

Closes #707 Remove "sitemap crawl interval" option field

---

inc/functions/posts.php

Fixes PHP Notice after 2.11.4 update caused by wrongly named variable. Replaced $tag with WP_Post object $post

Fix 695 - undefined variable $tag

---

inc/functions/formatting.php

Global variables $is_IIS and $is_iis7 are false on windows systems (localhost) that uses Apache (xampp). Checking for windows based on value of PHP_OS contant instead. Tested positively on localhost, apache and windows servers.

Fix #705 - rocket_realpath() compatibility on Windows servers

---

inc/3rd-party/3rd-party.php
inc/3rd-party/hosting/kinsta.php
inc/functions/options.php

- Disable WP Rocket cache
- Remove Varnish tab
- Trigger Kinsta Cache clear when WP Rocket clear cache is triggered
- Automatically detect Kinsta CDN

Closes #247 Kinsta compatibility

---

inc/classes/class-rocket-critical-css.php

Corrected the name of the public variable of the WP_Term class.

Fix #775 - Critical Path CSS Not Loaded For Custom Taxonomy Archive Page

---

inc/functions/formatting.php

Tested out all cases I could think of with this: https://github.com/wp-media/wp-rocket/issues/771#issuecomment-368004698

Fix #771 - rocket_get_home_path() breaks cache file generation

---

wp-rocket.php

It won't exist if the wordpress plugins are handled by composer, like in [Bedrock](https://github.com/roots/bedrock). With this change, the plugin will work both ways.

Require autoloader only if it exists.

---

inc/3rd-party/plugins/security/wps-hide-login.php

Fixes issue: Default value is not passed if WPS Hide Login's login url is empty.

Fix #783 - Homepage is not cached if WPS Hide Login's login url is empty

---

inc/functions/files.php
inc/functions/minify.php

the rewrite method uses `$_SERVER['DOCUMENT_ROOT']` if no parameter is passed for the document root. This causes issues sometimes as seen in #787.
To fix it, I'm passing ABSPATH as the document root parameter, filtered if needed, using a filter used before.

Fixes #915 & #787

---

inc/3rd-party/hosting/kinsta.php

In this PR:
- Fix fatal error if Kinsta mu-plugin is not there (after a migration for example)
- Display a warning on WP Rocket settings page if the mu-plugin is not there, to ask the customer to get in touch with Kinsta about this
- Fix cache clear not working when using the "Purge this URL" link on the front-end

Fixes #947 improve Kinsta compatibility

---

inc/3rd-party/hosting/siteground.php

I couldn't find a constant where SG Optimizer stored its version number so used the `get_file_data()` WordPress function.

Closes #925 - Force WP Rocket caching on SG Optimizer version below 4.0.5

---

inc/functions/files.php
inc/functions/minify.php

@Screenfeed do you see any problem with using `SCRIPT_FILENAME` here?

Fix #993 correctly rewrite referenced file paths in CSS files

---

inc/functions/i18n.php

Make sure that `$current_lang` contains a string, and nothing else.
Closes #1035 when merged.

Fix illegal offset type

---

inc/common/emoji.php

This update removes the prefetch request "https://s.w.org/" & removes the inline CSS block that is loaded with it as well for the emoji. 
CSS in question:  img.wp-smiley,img.emoji{display:inline!important;border:none!important;box-shadow:none!important;height:1em!important;width:1em!important;margin:0 .07em!important;vertical-align:-0.1em!important;background:none!important;padding:0!important}

Remove Emoji CSS & DNS Prefetch Request

---

inc/classes/class-plugin.php
inc/classes/optimization/JS/class-combine.php
inc/classes/subscriber/Optimization/class-combine-google-fonts-subscriber.php
inc/classes/subscriber/Optimization/class-minify-css-subscriber.php
inc/classes/subscriber/Optimization/class-minify-html-subscriber.php
inc/classes/subscriber/Optimization/class-minify-js-subscriber.php
inc/classes/subscriber/Optimization/class-scripts-escaping-subscriber.php
inc/classes/traits/trait-config-updater.php

DOMDocument doesn't like closing HTML tags in inline scripts (because it's not valid in HTML 4, which it still relies on).
To work around that, we escape early any closing tag found in inline scripts, and unescape them either:
- before they're combined into the combined JS file
- before returning the buffer content at the end when all optimizations have been done

Fix #1070 Prevent DOMDocument bug with closing HTML tags in inline scripts

---

inc/classes/optimization/JS/class-combine.php

Strange issue with the NewsPaper theme, if someone has Lazy Loading in WPRocket enabled, images in that JS will be encoded (for lazy loading like they should be example
however, there is a JS error once it meets that base64 encoded image and it causes none of the images to load and a bunch of strange issues this simply excludes any of the inline JS that loads this to resolve the issue. (Everything else appears to load normally) (Additionally, this issue doesn't seem to appear without Lazy Load enabled).

NewsPaper Theme JS Error With Combine JS & Lazy Loading

---

inc/classes/subscriber/class-google-tracking-cache-busting-subscriber.php

When the option is not active it was returning nothing instead of returning the array of schedules provided as a parameter.

Fix #1104 custom cron schedules removed when Google Tracking addon is not active

---

inc/classes/admin/deactivation/class-deactivation-intent.php

On multisite, the plugin couldn't be deactivated after being network-activated. This was due to the form not being printed in the page: the JS prevents the click on the deactivation link, and then fails to display the survey.

Fixes #1100: plugin network deactivation

---

views/settings/page.php

Only display the slider if the license key has been validated

Fix #1092 Prevent display of the show sidebar slider on license screen

---

inc/deprecated.php

Make sure to import the namespace for the minify class to prevent a fatal error if a deprecated function using it is called

Fixes #1111 PHP Fatal Error in deprecated function call

---

inc/classes/optimization/JS/class-combine.php

This excludes the inline JS added for coupons.com advertisements, to resolve display issues for advertisements.

Coupons.com Advertisement Fix

---

inc/classes/optimization/JS/class-combine.php

It's a type used for templates, that should not be combined

Exclude text/x-template type from combine JS

---

inc/3rd-party/plugins/ecommerce/give.php

Only hook if we're in an admin context

Fix #1141 Prevent PHP fatal error for get_home_path()

---

inc/front/deferred-js.php
inc/functions/options.php

This allows partial match and the use of wildcards for defer JS exclusion

Fixes #1022 & #1117 Defer JS exclusion using regex

---

inc/functions/htaccess.php

`get_rocket_option( 'cdn', false )` will return 0 (zero) instead of false if the option exists already in the database

Fixes #1086 incorrect conditional in get_rocket_htaccess_web_fonts_access()

---

inc/3rd-party/plugins/cookies/weepie-cookie-allow.php

This Pull request fixes the compatibility of our our [WeePie Cookie Allow plugin](https://codecanyon.net/item/weepie-cookie-allow-easy-complete-cookie-consent-plugin/10342528),
--
Lately we've improved our **WeePie Cookie Allow plugin** regarding **caching compatibility** by moving the PHP logic to the JavaScript. In short this means:
- The bar/box is now in depended form the server: the JavaScript decides, based on the cookie values, to show/not show the bar/box
- The blocking/un-blocking of content in the HTML (scripts, iFrames, etc) is 'prepared' server-side, but the JavaScript decides again to block/un-block the content
This means that, also with cached pages, our WeePie Cookie Allow plugin should function well. 
The only thing is that the cache (I think) should be cleared when:
- a …

Fixed WeePie Cookie Allow plugin compatibility

---

inc/front/process.php

- Remove safe-to-ignore parameters from the requested URL
- Reorder remaining parameters alphabetically
This improves 2 things:
- An URL with a parameter to be cached will no longer contained unneeded parameters, which was previously creating different cache files for nothing
- The same cache file will be used whatever the order of the parameters is, instead of creating a new one if the order is different

Fixes #1234 Improve query strings handling in process.php

---

inc/front/process.php

`readgzfile()` will decompress the file content before outputting it, which is flagging the HTML as uncompressed in PageSpeed.
By using the `Content-Encoding: gzip` header, we can read the file with `readfile()` and the compressed content will be displayed correctly in the browser, while also fixing the PageSpeed recommendation.

Fixes #45 Serve gzipped HTML file

---

inc/front/process.php

Along with the 304 response, we send the Expires and the Cache-Control headers too.
GitHub issue - https://github.com/wp-media/wp-rocket/issues/762

Fix #762 by sending Expires and Cache-Control headers

---

inc/3rd-party/hosting/flywheel.php
inc/3rd-party/hosting/godaddy.php
inc/3rd-party/hosting/kinsta.php
inc/3rd-party/hosting/o2switch.php
inc/3rd-party/hosting/pressidium.php
inc/3rd-party/hosting/savvii.php
inc/3rd-party/hosting/siteground.php
inc/3rd-party/hosting/wp-serveur.php
inc/3rd-party/hosting/wpengine.php
inc/admin/upgrader.php

#1088 
The mandatory cookies can prevent optimizations from being applied on the first load that will be cached by the server-side caching in place.
By removing them on those specific hostings we can be sure optimizations are always applied.

Fixes #1088 Remove Mandatory cookies on hosting with server side cache

---

inc/classes/subscriber/third-party/plugins/security/class-sucuri-subscriber.php
inc/functions/files.php

Also created the hooks `before_rocket_clean_files` and `after_rocket_clean_files`.

Fixes #1338: Too many requests to clear Sucuri cache on post update

---

inc/classes/preload/class-full-process.php
inc/classes/preload/class-homepage.php

We were not checking for the correct cache file in the preload when the website was using https. This would cause requests to be made even though the file is already in cache.

Correctly check for https cache version during preload

---

inc/classes/admin/settings/class-beacon.php

The Cloudflare documentation is missing from the Cloudflare Add-on section. 
Clicking the `NEED HELP?` link redirects to the WP Rocket Dashboard.

Add documentation for the Cloudflare Add-on

---

inc/classes/optimization/JS/class-combine.php

When the Testimonials Widget plugin is used, the `widget.reviewability.com` URIs are combined.
This results in the reviews not being displayed and the same goes for a review pop-up.
Excluding the following from combination, resolves the issue:
`widget.reviewability.com`
**Related ticket:**
https://secure.helpscout.net/conversation/718536510/88298?folderId=273766

Exclude "widget.reviewability.com" from JS combination

---

inc/classes/optimization/JS/class-combine.php

The following plugin: https://wordpress.org/plugins/report-broken-links/
This plugin includes inline JS that includes that page's URL (for obvious reasons) this simply excludes this inline JS to avoid, the cache from generating a unique JS file per page / post / archive / etc

Exclude Report Broken Link JS

---

inc/classes/optimization/JS/class-combine.php

Excludes the inline JS for wpRestNonce as this is dynamic and causes the cache to spin out of control on sites that are using the NewsPaper theme.
**Thank you for wanting to contribute to WP Rocket! Before submitting a pull request, please check that you’ve completed the following steps:**
- Please make sure that there aren’t existing pull requests attempting to address the issue mentioned.
- Check for related issues on the issue tracker.
- Non-trivial changes should be discussed on an issue first.
- Let us know you’re working on the issue.
- Develop in a topic branch, not master.
**Things to add in the pull request to help us:**
- Provide useful pull request description.
- Follow project commit guidelines.
- Write a good description of your PR.
- Link to the Github issue in the …

Exclude wpRestNonce (found in newspaper theme)

---

inc/functions/formatting.php

Assets with a relative URL, without a starting slash, were not optimized because the generated URL in formatting.php was incorrect

Minifies/Combines/Cache busts assets with a relative URL

---

inc/classes/logger/class-logger.php
inc/functions/files.php
inc/functions/htaccess.php

- Introduced `rocket_has_wp_htaccess_rules()` to detect WP rules.
- Improved `flush_rocket_htaccess()`. It also now returns a boolean based on the success of the process. Also renamed the parameter for something a bit easier to understand.
- Improved the emty lines removal behind the filter `rocket_remove_empty_lines`.
- Fixed WPR adding multiple empty lines after its rules when the filter `rocket_remove_empty_lines` is filtered to `false`.
- Introduced `rocket_get_filesystem_perms()` to get the permissions to apply to files and dirs.
Regex tests:
- https://regex101.com/r/xJoQze/1
- https://regex101.com/r/6FpB2r/1

Fixes #928: How to prevent htaccess corruption?

---

inc/3rd-party/3rd-party.php

Added a line of code, making sure that the entry of Rank Math shows up properly in WP Rocket's preload settings.
Closes #1445

Closes #1445 Include the Rank Math SEO file

---

inc/functions/i18n.php

`search_url` provides the base URL without slug for the language

Fixes #531 Correctly clean cache when slug is in homepage URL with Polylang

---

inc/classes/preload/class-homepage.php
inc/classes/preload/class-sitemap.php
inc/classes/subscriber/preload/class-preload-subscriber.php

Add a transient to store the error messages when an URL can't be reached or the content is not good, and display them in the preload running notice.

Closes #1377 Display error messages when preload fails

---

inc/classes/optimization/JS/class-combine.php

`fwduvpMainPlaylist`
*Ultimate Video Player plugin*
- https://www.diffchecker.com/Uz1UpIAj
`Bibblio.initRelatedContent`
*https://cdn.bibblio.org/rcm/3.7/bib-related-content.js*
- https://www.diffchecker.com/saF54oX8 
`showUFC()`
*Ultimate Facebook Comments plugin*
https://wordpress.org/plugins/ultimate-facebook-comments/
- https://www.diffchecker.com/9tuPjbOo
*Related ticket*
https://secure.helpscout.net/conversation/753365491/92859/?folderId=273766
---
`#iphorm-`
*iPhorm plugin*
https://codecanyon.net/item/quform-responsive-ajax-contact-form/
- https://www.diffchecker.com/8qKUzn82
- https://www.diffchecker.com/N5wNpxJX
`#fancy-`
*Fancy news plugin*
https://wordpress.org/plugins/fancy-news/
- https://www.diffchecker.com/UoDob0f9
`ult-carousel-`
*Ultimate VC Addons*
- …

Exclude strings from combination to avoid the large size of /cache/min/

---

inc/classes/preload/class-sitemap.php
inc/classes/subscriber/preload/class-sitemap-preload-subscriber.php

Also display a notice if the sitemap preload option is activated and the module is not enabled

Fixes #1368 Prevent fatal error if SimpleXML extension is not loaded

---

inc/classes/ServiceProvider/class-hostings-subscribers.php
inc/classes/class-plugin.php
inc/classes/subscriber/third-party/Hostings/class-pressable-subscriber.php
inc/functions/formatting.php

* Prevent WP Rocket cache files creation
* Prevent display of notices related to `advanced-cache.php`
* Prevent display of Varnish and NGINX add-ons as they don't make sense on Pressable
* Auto-purge Pressable cache when WP Rocket purge cache action is triggered
* Auto-detect Pressable CDN value
* Modify absolute path for assets in `wp-includes` to fit with Pressable setup

Pressable compatibility

---

inc/classes/optimization/JS/class-combine.php

Uplaunch is an inline form program similar to hubspot forms its js can't be combined or deferred. If combined the form doesn't render. If it's deferred the form ends up loading twice for some strange reason.

Exclude Uplaunch From Combine JS

---

inc/functions/options.php

Uplaunch can't be deferred or else the form will render twice and return a JS error on submission. The other PR deals with ignoring the combine JS which also breaks it.

Excludes Uplaunch From Defer JS

---

inc/common/purge.php

Also change function signature to add the second parameter `$post` while staying backward compatible

Fixes #1558 Prevent rocket_clean_post from running multiple times for the same post

---

inc/3rd-party/hosting/flywheel.php

* Prevent WP Rocket cache files creation
* Remove WP Rocket hooked function on clean post hooks.

Fixes #1581 Improve Flywheel compatibility

---

inc/3rd-party/plugins/seo/rank-math-seo.php

This PR fixes the compatibility issue between WP Rocket & Rank Math. The preloading of the Sitemap was not working with the latest versions of the plugins.
It is related to this issue:
https://github.com/wp-media/wp-rocket/issues/1620

Fixes #1620: Class not found error when WP Rocket's preloading of the Sitemap was activated

---

inc/classes/ServiceProvider/class-addons-subscribers.php
inc/classes/ServiceProvider/class-admin-subscribers.php
inc/classes/ServiceProvider/class-common-subscribers.php
inc/classes/ServiceProvider/class-hostings-subscribers.php
inc/classes/ServiceProvider/class-optimization-subscribers.php
inc/classes/ServiceProvider/class-preload-subscribers.php
inc/classes/ServiceProvider/class-third-party-subscribers.php
inc/classes/class-plugin.php

With that method, a third party can access the container and the instances of the classes by using
`$container = apply_filters( 'rocket_container', '' );`
This allows to access the subscribers, and remove hooks for example, as the correct instance of the classes can be referenced that way.

Give access to WP Rocket DI container

---

inc/classes/admin/Database/class-optimization-process.php

Code was moved to namespace in 3.3, so WP_Post was not referencing the correct namespace

Fixes #1657 Incorrect number of revisions deleted

---

inc/classes/subscriber/Optimization/class-critical-css-subscriber.php

Escape backslash characters to prevent `preg_replace` from interpreting the CSS as a matched pattern

Fixes #1659 Incorrect replacement in critical CSS output

---

inc/3rd-party/hosting/wpengine.php
inc/main.php

Transition from staging to live/live to staging was causing issues on WP Engine as the paths were not updated.
Since 3.3, we don't need anything in this file on WP Engine anyway, since the caching is deactivated, and the optimization is separate. So we can just rewrite an empty file.
Also fixes #1642

Fixes #1655 advanced-cache.php issues on WP Engine

---

inc/classes/subscriber/third-party/Hostings/class-pressable-subscriber.php

From `wp_rocket_loaded` to `admin_init`, as the previous one was not preventing display on plugin activation.

Change hook to remove advanced-cache.php notices on Pressable

---

inc/admin/upgrader.php
inc/functions/options.php

Embedded URLs are loaded in an iframe on the page, optimizing them can cause display issues

Fixes #1632 Exclude embedded URLs from caching/optimize

---

inc/common/purge.php

It should never happen but it seems to happen anyway

Fixes #1542 Prevent PHP warning if themes value is not an array

---

inc/3rd-party/themes/divi.php
inc/classes/optimization/class-remove-query-string.php

Also exclude the file from minification and remove query strings if Optimize CSS Delivery is active.
At the same time, correct an issue in the remove query strings class that was preventing files from being added to the exclusion, as the filter was not executed at all.

Fixes #1598 Exclude Divi main style from Optimize CSS Delivery

---

.travis.yml
composer.json
composer.lock
inc/classes/admin/class-options-data.php
inc/classes/admin/class-options.php
inc/classes/optimization/CSS/class-combine.php
tests/Fixtures/Optimization/CSS/combined.html
tests/Fixtures/Optimization/CSS/original.html
tests/Integration/Optimization/CSS/Combine/TestInsertCombinedCSS.php
tests/Unit/Optimization/CSS/Combine/TestInsertCombinedCSS.php

Fixes #1514 Use preg_replace to insert the combined CSS tag

---

inc/classes/optimization/JS/class-combine.php

The patterns **gform_ajax_frame_** and **gform_post_render** need to be auto-excluded from the **Inline JS to move after the combined JS file** to avoid the cache dir size issue.
https://www.diffchecker.com/2kN45mzx#left-2
https://www.diffchecker.com/e2eyTulH#left-2
Related ticket:
https://secure.helpscout.net/conversation/845256971/106654/

Auto-exclude gform_ajax_frame_ & gform_post_render inline JS

---

inc/classes/optimization/JS/class-combine.php

Alexa Metrics is using an inline JS script to validate a website's certification.
By default when we have the combine JS option turned on, this inline JS is included into our minified file. Then, the certification can't be validated.
We need to auto-exclude it by using the pattern: **_atrk_opts**
Related ticket support:
https://secure.helpscout.net/conversation/844467252/106548?folderId=273768

Compatibility with Alexa Metrics Certification

---

inc/classes/optimization/JS/class-combine.php

mts_view_count contains the post id.
quicklinkOptions contains the current URL.
Both should be auto-excluded to avoid cache dir size issue.
Related ticket:
https://secure.helpscout.net/conversation/834984595/105328/

Auto-exclude quicklinkOptions & mts_view_count inline JS

---

inc/classes/optimization/JS/class-combine.php

The pattern is included into jQuery function. Need to be excluded after the concatenated JS file.
https://www.diffchecker.com/X4TZhxDK#left-2

Autoexclude act_css_tooltip from Inline JS

---

inc/classes/optimization/JS/class-combine.php

`dataTable({`
https://www.diffchecker.com/PTJsGHOA
TablePress plugin
/wp-content/plugins/tablepress/js/jquery.datatables.min.js
---
`var rankMath = {`
https://www.diffchecker.com/lPVGCbve
Rank Math
https://wordpress.org/plugins/seo-by-rank-math/
---
**Related ticket**
https://secure.helpscout.net/conversation/834984595/105328/

Exclude inline patterns from being combined.

---

uninstall.php

For Facebook and Google Tracking add-ons

Fixes #1644 Clear cron events on uninstall

---

inc/admin/options.php
inc/admin/upgrader.php
inc/classes/admin/settings/class-page.php

Fixes #1685 Auto-active SSL cache for new installations

---

inc/3rd-party/plugins/autoptimize.php
inc/3rd-party/themes/avada.php
inc/classes/admin/settings/class-page.php

Deactivate WP Rocket lazyload if Autoptimize or Avada lazyload is enabled

Fixes #1707 Autoptimize & Avada lazyload compatibility

---

inc/functions/options.php
tests/Integration/Functions/Options/TestExcludeDeferJS.php
tests/Unit/Functions/Options/TestExcludeDeferJS.php
tests/Unit/Optimization/CSS/Combine/TestInsertCombinedCSS.php
tests/Unit/bootstrap.php

Exclude jQuery loaded from `wp.com` CDN and from `ajax.googleapis.com`

Fixes #1196 Exclude common external jQuery from defer JS safe mode

---

inc/classes/ServiceProvider/class-common-subscribers.php
inc/classes/class-plugin.php
inc/classes/subscriber/Tools/class-cache-dir-size-check-subscriber.php
inc/main.php
uninstall.php

Performs a weekly check for the `min` and `busting` directories sizes, and send a notification if they are above the defined maximum size, which is 1GB for now

Monitor cache directory size

---

inc/admin/ui/notices.php
inc/functions/htaccess.php

Closes #1555 
Closes #1651 
- Check if the WP Rocket rules are already present in the htaccess before displaying the notice
- Update the notice wording and switch the type from error to warning

Update htaccess WP Rocket missing rules notice

---

inc/classes/optimization/JS/class-combine.php

From:
1
- https://wp-media.slack.com/archives/CK74JC6JK/p1560557937078100
- No diff check available (the website was down)
2
- https://wp-media.slack.com/archives/CK74JC6JK/p1560558662078300
- https://www.diffchecker.com/wmhdR6Pz#left-2
3
- https://wp-media.slack.com/archives/CK74JC6JK/p1560562318078400
- https://www.diffchecker.com/pB3AqGb2#left-3
4
- https://wp-media.slack.com/archives/CK74JC6JK/p1560584837094200
- https://www.diffchecker.com/5BD1e5VX#left-3

Auto-exclude 4 new Inline JS patterns

---

inc/admin/ui/meta-boxes.php

This is just a minor change of the **Minify HTML** feature wording in WP Rocket's options meta-box.

Change the wording for Minify HTML in the options meta-box.

---

inc/functions/files.php

There was a double ";" in the `advanced-cache.php` file.

Fix a small typo: ";" added twice

---

inc/classes/optimization/CSS/class-critical-css.php

Exclude the following CPTs from the CPCSS generation:
* `fusion_template` - Avada Fusion Builder
* `blocks` - Flatsome UX Blocks
Exclude custom taxonomy:
* `element_category` - Avada Fusion Builder
**Related tickets:**
* https://secure.helpscout.net/conversation/883742688/113030?folderId=2135277
* https://secure.helpscout.net/conversation/886155490/113352?folderId=2135277

Exclude CPTs and custom taxonomies from CPCSS generation

---

inc/classes/optimization/JS/class-combine.php

Exclude "Springbot.product_id" inline JS to avoid the cache directory size issue.
**Diff file:**
https://www.diffchecker.com/a7TCCJQG
**Related Ticket:**
https://secure.helpscout.net/conversation/893164866/114243?folderId=2135277

Exclude "Springbot.product_id" inline JS to avoid the cache directory size issue

---

inc/admin/upgrader.php
inc/functions/admin.php

`home_url()` value is unreliable because of plugins used to apply SSL/HTTPS without updating the options values.

Fixes #1193 Check for SSL using the $_SERVER superglobal values

---

inc/classes/optimization/JS/class-combine.php

https://www.diffchecker.com/bwJ3UKhA
function reenableButton
https://www.diffchecker.com/0XTgKXsF
Exclude: #wpnbio-show / Plugin Render SeedProd Notification Bar Pro
https://www.screencast.com/t/FQV98UC27LB9
https://secure.helpscout.net/conversation/906601448/116512?folderId=3083222
e.Newsletter2GoTrackingObject

Exclude "function reenableButton", "#wpnbio-show", "e.Newsletter2GoTrackingObject" inline JS to avoid the cache directory size issue

---

inc/3rd-party/3rd-party.php
inc/3rd-party/plugins/cookies/cookie-consent.php
inc/3rd-party/plugins/cookies/uk-cookie-consent.php

Adds compatibility for the uk cookie consent plugin:
https://wordpress.org/support/plugin/uk-cookie-consent
There is only one cookie created on consent acceptance:

Add uk cookie consent compatibility

---

inc/classes/Buffer/class-config.php
inc/classes/Buffer/class-tests.php
inc/functions/files.php
inc/functions/options.php

Move the list of ignored query string parameters from hardcoded to the config file. The list is now filterable to be able to add/remove parameters as needed.

Closes #1597 Customization of ignored query string parameters during caching

---

inc/functions/files.php

Prevents and checks if the busting folder exists and is a directory. 
If busting folder does not exist it creates it and exists the clean busting function.
RecursiveDirectoryIterator throws a UnexpectedValueException if the path is not found or is not a directory
* Added logger info

Fixes #1829 - prevent UnexpectedValueException when busting folder is missing

---

inc/classes/CDN/CDN.php
inc/classes/optimization/CSS/class-abstract-css-optimization.php
inc/classes/optimization/CSS/class-minify.php
inc/classes/optimization/JS/class-abstract-js-optimization.php
inc/classes/optimization/JS/class-minify.php
inc/classes/optimization/class-remove-query-string.php
inc/classes/subscriber/CDN/CDNSubscriber.php
tests/Integration/Subscriber/CDNSubscriber/TestGetSubscribedEvents.php

- CDN is applied before the other optimizations
- The original URL is provided to the methods returning the minify/busting URL, and passed to the filters
- the filters check if the original URL is excluded, and return the not CDN URL if it is

Fixes #306 Handle CDN exclusions when using Remove Query Strings/Minify

---

inc/classes/optimization/JS/class-combine.php

`location_data.push`
https://www.diffchecker.com/CditTFOH
`thirstyFunctions.isThirstyLink`
https://www.diffchecker.com/CQ60gzKj
`styles: ' #custom-menu-`
https://www.diffchecker.com/WPj90oHR
```
function svc_center_
#svc_carousel2_container_
```
https://www.diffchecker.com/2ceKTZaK

Exclude inline strings to avoid the cache directory size issue

---

inc/classes/admin/settings/class-page.php

Fixes #1855 - The style of "Exclude Inline JS" isn't good when we turn on JS combination for the first time

Fixes #1855 - Style of "Exclude Inline JS"

---

inc/admin/options.php
inc/classes/admin/settings/class-settings.php
inc/functions/formatting.php

When the user submits new patterns (to exclude files for example), sanitize and test the values. In case of malformed patterns, don’t save them and display an error message.

Closes #1469: Provide UI feedback for preg_match warnings

---

inc/classes/Cache/class-expired-cache-purge.php
inc/classes/ServiceProvider/class-common-subscribers.php
inc/classes/class-plugin.php
inc/classes/subscriber/Cache/class-expired-cache-purge-subscriber.php
phpunit.xml.dist
tests/Integration/Subscriber/ExpiredCachePurgeSubscriber/TestGetCacheLifespan.php
tests/Integration/Subscriber/ExpiredCachePurgeSubscriber/TestGetSubscribedEvents.php
tests/Integration/Subscriber/ExpiredCachePurgeSubscriber/TestScheduleEvent.php
tests/Unit/Cache/TestPurgeExpiredFiles.php

- Split code between 2 classes
- Rename `Automatic_Cache_Purge` to `Expired_Cache_Purge`
- Reduce complexity in `Expired_Cache_Purge::purge_expired_files()`
- Add unit & integration tests

Add unit & integration tests for the Expired Cache Purge methods

---

inc/classes/busting/class-facebook-pickles.php

Fixes: #1819 - Facebook Pixel config file - changed INT to String to have the correct FB APP_ID

Changed INT to String for FB APP_ID

---

inc/3rd-party/themes/impreza.php

Fix the path of the core.min.js file of the impreza theme. This seems to have changed in the last version of the theme

Fix impreza file path

---

inc/classes/optimization/JS/class-combine.php

A corrected version of this PR:
https://github.com/wp-media/wp-rocket/pull/1911
Moved scripts that require jQuery to the proper array.

Added excluded JS

---

inc/classes/Buffer/class-cache.php
inc/classes/subscriber/Media/class-webp-subscriber.php
inc/functions/files.php
inc/functions/htaccess.php

When a page doesn’t contain webp files, don’t create a webp cache file identical to its non-webp version. Instead, create an empty `.no-webp` file and serve the non-webp cache.
Also fix an issue where webp files would be delivered to browsers not compatible with webp.

Prevent duplicating cache files without webp

---

inc/classes/subscriber/third-party/plugins/Images/Webp/class-shortpixel-subscriber.php

This is to make sure Rocket’s webp cache option is disabled if needed.

Improved Shortpixel’s webp option sync

---

inc/classes/subscriber/Media/class-webp-subscriber.php

The header `Accept` was missing and has been added.
Also, the request to the home page was not filtered, it has been corrected.

Fix preloader not preloading webp cache

---

inc/classes/Buffer/class-cache.php
inc/classes/subscriber/Media/class-webp-subscriber.php

`apache_request_headers()` doesn’t seem to be reliable, while `$_SERVER` seems to be. So let’s use `$_SERVER` first, then `apache_request_headers()` only as fallback.

Improved the way to get the "webp header"

---

inc/classes/optimization/JS/class-combine.php

`searchwp_live_search_params`
https://www.diffchecker.com/S9DskgXe
`wpp_params`
https://www.diffchecker.com/dC1r6WPl

Exlude inline JavaScript keywords

---

inc/common/admin-bar.php

Add a WordPress Quick actions menu item to purge Sucuri cache. I mean here - https://jmp.sh/baWbUhW (To take advantage of the rocket_purge_sucuri_cache capability)
Based on:

Add a WordPress Quick actions menu item to purge Sucuri cache

---

inc/functions/files.php

Cache Busting folder structure contains a directory we cannot recurse into, permissions do not allow to recurse the structure of busting folder.
E_ERROR was caused in line 554 of the file wp-content/plugins/wp-rocket/inc/functions/files.php
Full error is available here - https://secure.helpscout.net/conversation/963849440/124175/
Related conversation - https://wp-media.slack.com/archives/C08N8J6VC/p1569790610001900
Based on:

Cache Busting folder structure contains a directory we cannot recurse into.

---

inc/vendors/classes/class-minify-html.php

Minify HTML will break at trimming each line when attributes span on multiple lines:
This line is causing the issue:
wp-rocket/inc/vendors/classes/class-minify-html.php
$this->_html = preg_replace('/^\\s+|\\s+$/m', '', $this->_html); 
SOLUTION:
// Fixed attribute values which span on multiple lines. Causes double spaces "  "
$this->_html = preg_replace('/^\\s+|\\s+$/m', ' ', $this->_html);
// Fixed double spaces. Replaced with a single space
$this->_html = preg_replace('/  +/', ' ', $this->_html);

Fixes #1931: Minify HTML do not take into account attribute values that span multiple lines

---

inc/classes/subscriber/Optimization/class-critical-css-subscriber.php

Added admin notices for CPCSS generation allowed outside WP Rocket settings page
Issue demo - https://jmp.sh/JZiRHTc
Based on:

Display admin notice for CPCSS outside WP Rocket admin page

---

inc/vendors/classes/class-minify-html.php

Big inline JS scripts are causing PREG_BACKTRACK_LIMIT_ERROR and the page will be empty.
preg_replace_callback - on errors the return is NULL
Solution: if preg_replace_callback return is NULL, then do not minify any inline JS code to prevent this issue. 
The issue was identified from: WooCommerce Blocks plugin:
https://wordpress.org/plugins/woo-gutenberg-products-block/
There is excessive JS (1.5MB of JS) from it causing the issue with WP Rocket: https://wordpress.org/support/topic/causes-excessive-js/

Fixes #1940: Minify inline JS & CSS - prevent PREG_BACKTRACK_LIMIT_ERROR

---

inc/classes/subscriber/Optimization/class-lazyload-subscriber.php

Fixes #1949 - when LazyLoad is disabled on a specific page, remove lazyload.js and inline JS code related to lazy load

Fixes: #1949 remove lazyload.js file & code when Lazyload is disabled on a specific page

---

inc/functions/formatting.php

Autocorrect wildcard rules on Never Cache Url(s)
Incorrect wildcard rules as * , .* will be automatically replaced by the correct rule (.*)
Based on:

Fix 1917 - Autocorrect wilcard rules on never cache urls

---

assets/css/wpr-admin-common.css
inc/admin/ui/notices.php

Improve notice when Cloudflare plugin is detected
Edited the current notice view and plugin name is in bold now with an explainer text beside it. Increased the width of .rocket-plugins-error li from 280px to 100% to allow the explainer text to fit inside:
https://www.screencast.com/t/0hKXgvhfGc6Y
Based on:

Fix #1566 - Improve Cloudflare disable notice

---

inc/classes/subscriber/CDN/CDNSubscriber.php
inc/classes/subscriber/Media/class-webp-subscriber.php
inc/classes/subscriber/Optimization/class-combine-google-fonts-subscriber.php
inc/classes/subscriber/Optimization/class-critical-css-subscriber.php
inc/classes/subscriber/Optimization/class-ie-conditionals-subscriber.php
inc/classes/subscriber/Optimization/class-lazyload-subscriber.php
inc/classes/subscriber/Optimization/class-minify-html-subscriber.php
inc/classes/subscriber/Optimization/class-minify-js-subscriber.php
inc/classes/subscriber/Optimization/class-remove-query-string-subscriber.php
inc/front/deferred-js.php
tests/Integration/Subscriber/CDNSubscriber/TestGetSubscribedEvents.php

Current priorities were causing an issue when critical CSS and combine CSS were active at the same time, since 3.4.
Critical CSS priority was changed during 3.4 beta because of an issue with the new CDN priority.
This PR should fix any priority issue by updating all of them and making sure everything is applied in the correct order.
Extract IE => 1
Facebook => 10
Google => 10
JS min/combine => 12
Defer JS => 14
CSS min/combine => 16
Critical CSS => 18
Google fonts => 20
Remove Query Strings => 22
Async CSS => 24
Insert IE => 26
WebP => 28
Lazyload => 30
CDN => 32
HTML min => 34

Update filters priorities

---

inc/classes/admin/settings/class-settings.php
inc/functions/cloudflare.php

Added Cloudflare validation API when saving API key, email & zone.
Needs proper error messages. Error messages coming from Cloudflare are "generic" and can lead to confusion.
Based on:

Fix #934: Cloudflare validation API when saving - needs proper error messages

---

inc/classes/optimization/JS/class-combine.php

Added ConvertKit plugin domain URL to the exclusion list. There are a couple of tickets related to this plugin. No need to exclude it from deferring as it already has the async attribute.

Added external JS file exclusion

---

inc/common/admin-bar.php
views/settings/page-sections/dashboard.php

When OPCache clearing via API isn't possible because of opcache.restrict_api in php.ini, it's best to remove the Purge OPCache links from:
WP Rocket Admin bar - https://jmp.sh/o8NuVrq
Quick actions in WP Rocket dashboard - https://jmp.sh/uW2Skxv

Fix #2038 - Remove Purge OpCache when Restrict API is enabled

---

inc/common/purge.php

Cache cleaned when post slug / permalink is changed - cache cleaned for old post slug / permalink
Based on 3.4.2 Doc

Fixes #1936 - Cache cleaned when post slug / permalink is changed

---

inc/functions/options.php
tests/Integration/Functions/Options/TestExcludeDeferJS.php
tests/Unit/Functions/Options/TestExcludeDeferJS.php

Using JupiterX theme you can integrate your Adobe Fonts / Typekit:
`<script type='text/javascript' src='http://example.com/wp-content/themes/jupiterx/lib/admin/assets/lib/webfont/webfont.min.js?ver=1.6.26'></script>`
`<script type='text/javascript'> WebFont.load({ typekit: { id:'xxxxxxx' } }); </script>`
Remove `/wp-content/themes/jupiterx/lib/admin/assets/lib/webfont/webfont.min.js` from defer JS in order to prevent undefined WebFont.load.
Based on 3.4.2 Doc

Fixes #1912 Add webfont.min.js from defer js

---

inc/classes/optimization/JS/class-combine.php

Like previous patches this one excludes yet another optinmonster api url that can be used. When the JS is not excluded from combining it returns a JS error. 
[OptinMonster] A user attribute is required in the embed code.
Full JS URL: https://a.opmnstr.com/app/js/api.min.js

Exclude Optinmonster API From Combine

---

inc/3rd-party/plugins/seo/the-seo-framework.php

The SEO Framework (TSF) v4.0 will be released next week. In this PR, I added forward and backward compatibility for sitemap preloading, specifically, on how the sitemap URL is fetched.
In TSF, we added backward compatibility for the older integration, so WP Rocket users shouldn't notice a change in functionality. However, [deprecation notices](https://github.com/sybrew/the-seo-framework/blob/0b0473bd642d855165753a1cf37a937fdbd929ce/inc/classes/deprecated.class.php#L380) may appear when the user upgrades to TSF 4.0+ before updating WP Rocket with this PR included.
Previous PR: https://github.com/wp-media/wp-rocket/pull/1295
Previous Issue: https://github.com/wp-media/wp-rocket/issues/899

The SEO Framework 4.0 compat

---

inc/admin/options.php
inc/admin/upgrader.php
inc/classes/admin/settings/class-settings.php
inc/functions/cloudflare.php

- The upgrade routine will stop setting cache_ssl as true, if it's already true. This save of settings during upgrade was causing Cloudflare validation during update. This makes everything more efficient.
- Cloudflare validation will only happen if the API key / email / zone ID is changed. So it isn't validated every time other settings are saved. More efficient this way.

Cloudflare validation API done only when CF inputs are changed

---

inc/classes/subscriber/CDN/CDNSubscriber.php
inc/classes/subscriber/Media/class-webp-subscriber.php
inc/classes/subscriber/Optimization/class-combine-google-fonts-subscriber.php
inc/classes/subscriber/Optimization/class-critical-css-subscriber.php
inc/classes/subscriber/Optimization/class-ie-conditionals-subscriber.php
inc/classes/subscriber/Optimization/class-lazyload-subscriber.php
inc/classes/subscriber/Optimization/class-minify-css-subscriber.php
inc/classes/subscriber/Optimization/class-minify-html-subscriber.php
inc/classes/subscriber/Optimization/class-minify-js-subscriber.php
inc/classes/subscriber/Optimization/class-remove-query-string-subscriber.php
inc/front/deferred-js.php
tests/Integration/Subscriber/CDNSubscriber/TestGetSubscribedEvents.php

Current priorities of functions hooked on `rocket_buffer` prevent the CDN exclusions from working correctly if minify CSS/JS and/or Remove Query Strings options are enabled.
Updating the order allows the exclusions to work, with CDN being applied first, and the above optimizations after.
Other priorities are updated too, to keep everything working in the right order:
- WebP needs to be after HTML minification
- Lazyload before CDN
- Defer JS after minify/combine JS
- Critical CSS insertion after minify/combine CSS and combine Google fonts
- Remove Query Strings after the 2 above
- Async CSS after the 3 above

Fixes #306 Allow CDN exclusions to work with Minify/Remove Query Strings

---

inc/classes/Cache/class-expired-cache-purge.php
tests/Unit/Cache/TestPurgeExpiredFiles.php

- Remove the incorrect parameter used for `array_unique()`
- Update unit tests to add a test for multilingual setup

Fixes #2084 Correctly purge expired cache when using multilingual plugins

---

inc/classes/Buffer/class-cache.php

Firefox 70 wasn't recognized correctly, which resulted in WebP not being served there.

Change RegEx for recognizing Firefox version in WebP detection

---

inc/common/purge.php

Fixed clean archive page of a CPT with SLL, basically index.html and index.html_gzip must contain -https since SSL cache is active.
Based on 3.4.2

Fixed #1904 Clean the archive page of a CPT with SSL

---

inc/classes/Buffer/class-optimization.php
inc/classes/ServiceProvider/class-common-subscribers.php
inc/classes/class-plugin.php
inc/classes/subscriber/Tools/class-detect-missing-tags-subscriber.php
tests/Fixtures/Subscriber/Tools/original_both_html_and_body_commented.html
tests/Fixtures/Subscriber/Tools/original_commented_html_and_body.html
tests/Fixtures/Subscriber/Tools/original_html_and_body.html
tests/Fixtures/Subscriber/Tools/original_no_html_and_body.html
tests/Unit/Subscriber/Tools/TestDetectMissingTags.php

Detect and report when closing </html>, </body> and wp_footer() are not available.
I created a new hook in before Optimization process starts, which is hooked in "template_redirect" hook. It seems this hook is called only from template calls and I checked it out with REST API and with FEED and even if caching is enabled for these 2 it works fine (no false positive because this hook is not called)

Fixed #1985 - Detect and report when </html>, </body> and wp_footer() are not available.

---

inc/classes/subscriber/third-party/plugins/class-mobile-subscriber.php

Notice: Array to string conversion in /home/wpquicki/mega/wp-content/plugins/wp-rocket/inc/classes/subscriber/third-party/plugins/class-mobile-subscriber.php on line 224
When 3.4.2-alpha1 is installed and I rollback to 3.3.7, I get the following notice:

Fix #2103 Array to string conversion in mobile subscriber

---

inc/classes/subscriber/Tools/class-detect-missing-tags-subscriber.php

Fixed false positive reports for missing </html>, </body> or wp_footer() when there is a redirect and the content of the page is empty or less than 255 chars.

Fixed false positive for missing tags when there is a redirect

---

inc/classes/Cache/class-expired-cache-purge.php

Fixed: Fatal error at `getCTime()` in expired cache purge
`$item->getCTime()` throws a `RuntimeException`
`CRITICAL Uncaught RuntimeException: SplFileInfo::getCTime(): stat failed for /public_html/wp-content/cache/wp-rocket/.../index-https.html_gzip in /public_html/wp-content/plugins/wp-rocket/inc/classes/Cache/class-expired-cache-purge.php:329`

Fixed: Fatal error at getCTime() in expired cache purge

---

inc/classes/subscriber/third-party/plugins/class-mobile-subscriber.php

Mobile cache was not constantly created with Jetpack installed.
Htaccess rules were not removed and JetPack needs to check also if `is_active()`

Fixed Jetpack integration issues

---

inc/classes/admin/settings/class-page.php

Make sure to pass an integer timestamp to `date_i18n()`.

Fixes #2095: PHP Warning: date() expects parameter 2 to be int

---

inc/classes/subscriber/Tools/class-detect-missing-tags-subscriber.php
tests/Fixtures/Subscriber/Tools/original_both_html_and_body_commented.html
tests/Fixtures/Subscriber/Tools/original_commented_html_and_body.html
tests/Fixtures/Subscriber/Tools/original_html_and_body.html
tests/Fixtures/Subscriber/Tools/original_no_html_and_body.html
tests/Unit/Subscriber/Tools/TestDetectMissingTags.php

Fix: prevent false positive notices on missing tags </body>, </html> and wp_footer()

Fix: prevent false positive on missing tag notice

---

inc/admin/options.php
inc/classes/admin/settings/class-settings.php

Don't use `get_settings_errors()` when storing new errors.
Don't add a "Settings saved" notice if already present.

Fixes #2071: multiple admin notices

---

inc/classes/busting/class-facebook-sdk.php

Add FB.init() when Facebook Pizel Addon is enabled:
```
<script>
window.fbAsyncInit = function() {
FB.init({
appId            : 'your-app-id',
autoLogAppEvents : true,
xfbml            : true,
version          : 'v5.0'
});
};
</script>
```

Fixes: #1323,#1326 - Facebook Pixel Addon need to run FB.init()

---

inc/classes/Buffer/class-cache.php
inc/classes/subscriber/Media/class-webp-subscriber.php

Prevent blank page when multiple servers are using the same shared filesystem. Instead of directly writing in the final cache file, we first write in a temp file, and rename it when it's done.
Also fixes an undetected issue with WebP and Firefox version > 66

Fixes #1945 cache race condition with multiple servers

---

inc/common/purge.php

Fixes running rocket_clean_post() when saving drafts.
Cleaning rocket cache when a post status is changed from Publish to Draft.
There could be other statuses which could need to be excluded (eg. inherit)

Fixed #2124 - running rocket_clean_post() when saving drafts

---

inc/classes/admin/settings/class-page.php
views/settings/page.php

License Validation - Rename "Save Settings" to "Validate License"
Based on v.3.4.3 minor release doc

Fix #1479 - Rename "Save Settings" to "Validate License"

---

inc/classes/optimization/class-abstract-optimization.php

Prevent PHP warning: Can only flip STRING and INTEGER values!
This happened when: host = NULL so I added some conditions to prevent this.
parse_url returns:
NULL - if the value is not found
string/integer/null - if the value is found and component is specified
array - if the component is not specified
So I prevented the NULL and array value from adding it to hosts. 
Based on v3.4.3 doc

Fix #2118 - PHP warning: Can only flip STRING and INTEGER values!

---

inc/common/purge.php
tests/Unit/Common/TestRocketCleanPostCacheOnSlugChange.php

Fix clean rocket post cache when old slug is empty and old post_status is draft , pending or auto-draft (there is no cache to be cleaned in this situation).
Fixes #1936 [per discussion here](https://github.com/wp-media/wp-rocket/issues/1936#issuecomment-561142237).
Test Cases:
- with WooCommerce Follow-up Emails plugin
In order to test it go to: Tools > Scheduled Actions > Pending and run any of the 2 actions listed
- Publishing a new post causes the whole cache to be cleared.
TODO:
[X] Test locally with 2 test cases (see above)
[X] Identify needed post statuses
[X] Unit test
[ ] Integration test - @hellofromtonya This one will be in a new PR once a few updates are made to the integration bootstrapping process.

Fix clean rocket post cache on slug change when post name is empty & status is not published

---

composer.json
tests/Integration/Buffer/Tests/TestIsSpeedTool.php
tests/Integration/Functions/Options/TestExcludeDeferJS.php
tests/Integration/Optimization/CSS/Combine/TestInsertCombinedCSS.php
tests/Integration/Optimization/CSS/CombineGoogleFonts/TestOptimize.php
tests/Integration/Subscriber/CDNSubscriber/TestGetCDNHosts.php
tests/Integration/Subscriber/CDNSubscriber/TestGetSubscribedEvents.php
tests/Integration/Subscriber/CDNSubscriber/TestRewrite.php
tests/Integration/Subscriber/CDNSubscriber/TestRewriteCSSProperties.php
tests/Integration/Subscriber/CDNSubscriber/TestRewriteSrcset.php
tests/Integration/Subscriber/ExpiredCachePurgeSubscriber/TestGetCacheLifespan.php
tests/Integration/Subscriber/ExpiredCachePurgeSubscriber/TestGetSubscribedEvents.php
tests/Integration/Subscriber/ExpiredCachePurgeSubscriber/TestScheduleEvent.php
tests/Integration/TestCase.php
tests/Integration/bootstrap.php
tests/Integration/phpunit.xml.dist
tests/Unit/TestCase.php
tests/Unit/bootstrap.php
tests/Unit/phpunit.xml.dist
tests/boostrap-functions.php

This PR includes the following improvements for bootstrapping the test suites:
- Loads Patchwork first before anything else runs, ie to ensure it's ready before any user-defined (WP, 3rd, or WP Rocket) functions are loaded into memory. This change avoids wonky, weird behaviors that can happen when mocking functions.
- Centralizes bootstrapping tasks (by moving them into a common functions file that's called from each test suite's bootstrap file)
- Adds a new composer script to run all the tests: `composer run-tests`
- Changes the inheritance test case inheritance by:
- adding a new `TestCase`
- extending that class off of `WP_UnitTestCase`
- The new inheritance chain is: `WP_Rocket\Tests\Integration\TestCase` -> `WP_UnitTestCase` -> `WP_UnitTestCase_Base` -> `PHPUnit\Framework\TestCase` …

Improves bootstrapping test suites.

---

inc/classes/ServiceProvider/class-common-subscribers.php
inc/classes/class-plugin.php
inc/classes/subscriber/Cache/PurgeActionsSubscriber.php
inc/common/purge.php
tests/Unit/Subscriber/Cache/PurgeActionsSubscriber/TestPurgeUserCache.php

- Removed the global purge on user creation/update/deletion
- Delete the cache for a specific user when it's updated/deleted, only if User cache option is active, and common logged-in users cache is not
This should improve cache lifetime on websites with frequent user creation (eCommerce especially), while still retaining the necessary cleaning of the user cache on sites with user-specific content like memberships or BuddyPress-based ones.
Fixes #2139

Fixes #2139 Update logic on user actions purge

---

inc/functions/files.php

Format the code added by WP Rocket to wp-config.php according to the WordPress Coding Standards.
Thank you, Vasilis, for indulging me!

Format code added to wp-config.php to match WPCS

---

inc/classes/admin/settings/class-beacon.php

This will be used to send messages in Beacon, with specific targetting depending on the customer status (new/active/expired).
The status is fetched from the API, and stored in the `wp_rocket_customer_data` transient. The fetch and cache of the data is done in `WP_Rocket\Admin\Settings\Page`.
Ideally I would need to do some decoupling there and make sure I always have a value for the `status`, but as it's non-critical data and we're already in the testing phase for 3.4.3, I went for the easiest solution (for now).

Add customer status to Beacon identify

---

inc/classes/subscriber/Cache/class-expired-cache-purge-subscriber.php
tests/Integration/Subscriber/ExpiredCachePurgeSubscriber/TestCleanCacheScheduledEvent.php

Cleaning the scheduled event from clean expired cache when cron unit is set to minutes.
For hours & days the scheduled event should be set to 1 hour, but for minutes should be set to those exact minutes.
My latest changes got removed from the last PR #2180
Arun pointed out that when changing from Minutes to Minutes and if the interval is changes the scheduled event should be cleaned. Added the code + Integration tests for it.

Fixed: clean expired cache scheduled event when cron unit is set to minutes

---

inc/classes/subscriber/Addons/Cloudflare/CloudflareSubscriber.php
tests/Unit/Subscriber/Addons/CloudflareSubscriber/TestAutoPurge.php
tests/Unit/Subscriber/Addons/CloudflareSubscriber/TestAutoPurgeByUrl.php

Cleaning Cloudflare cache when a post cache is cleaned needed also the home URL and the feeds URLs

Fixed: Cloudflare Auto Purge By Url add home and feed urls to purge urls list

---

inc/classes/subscriber/Cache/class-expired-cache-purge-subscriber.php

Remove extra condition from clean expired cache scheduled event:
> If A = B and A is in C, then B is in C.
Bail out conditions are already preventing this situation, so this condition is useless (thanks Greg for pointing this out).

Removed extra condition from clean expired cache scheduled event when cron unit is set to minute

---

inc/classes/CDN/CDN.php
tests/Fixtures/CDN/original.html
tests/Fixtures/CDN/rewrite.html
tests/Fixtures/CDN/srcset/rewrite.html

Fixes multiple CDN url replacement on srcset rewrites.
Applied array_unique() after I made a trim() on the sources array.

Fix #2107 CDN srcset rewrites

---

inc/classes/admin/settings/class-page.php

Changed text to:
Most modern themes are responsive and should work without a separate cache. Enable this only if you have a dedicated mobile theme or plugin. More info
More info links to https://docs.wp-rocket.me/article/708-mobile-caching/?utm_source=wp_plugin&utm_medium=wp_rocket (This link https://jmp.sh/5qe7CW3)
Reference Issue ticket #2134

Fix #2134 - Improve "Separate cache files for mobile devices" help text

---

inc/3rd-party/plugins/autoptimize.php

Cleaning Autoptimize cache with the menu bar link, will not clean WP Rocket cache and will cause 404 errors related to JS and CSS files.
The menu bar link is triggered with admin-ajax.php and at that point the function `autoptimize_do_cachepurged_action` is not defined. I've modified it to `class_exists( 'autoptimizeCache' )`
Reference issue #2167

Fix #2167 - After clearing Autoptimize cache, rocket_clean_domain is not being called

---

inc/admin/options.php

Fix #2159 - Don't clear the cache when preload option is changed
When you turn on or off the preload option, the cache is cleared, but there's no benefit to or need for doing that.

Fix #2159 - Don't clear the cache when preload option is changed

---

inc/classes/subscriber/Plugin/class-updater-subscriber.php
wp-rocket.php

Updated Wordpress Compatibility
I added a new constant: `WP_ROCKET_WP_VERSION_TESTED` which includes the latest version of Wordpress and how it displays like this: https://www.screencast.com/t/y3gCQ5ZOpG6R
This can also be fetched from update API or directly from Wordpress with `get_core_updates()` function. 
Reference Issue #1550 
**Which should be the best approach?**

Fixed #1550 Update Wordpress Compatibility

---

inc/vendors/classes/class-minify-html.php

Keep the comment to preserve compatibility with FacetWP
```html
```
Reference issue #2121

Fix #2121 - Exclude fwp-loop comment from stripping for FacetWP

---

inc/functions/options.php
tests/Integration/Functions/Options/TestExcludeDeferJS.php
tests/Unit/Functions/Options/TestExcludeDeferJS.php

This excludes the CDNJS version of jQuery from defer if the jQuery safe JS option is checked.

Fixes #2029 Exclude CDNJS Version of jQuery From Defer

---

inc/classes/subscriber/CDN/CDNSubscriber.php
tests/Integration/Subscriber/CDNSubscriber/TestRewrite.php
tests/Integration/Subscriber/CDNSubscriber/TestRewriteSrcset.php

Integration tests take a long time to run due to :
```
/**
* @runInSeparateProcess
* @preserveGlobalState disabled
*/
```
I inverted the @runInSeparateProcess to be available only for the function which defines the constant and it decreased the running time to 1.1s all integration tests (before it was about 9minutes)

Fixed: decreased integration tests running time

---

inc/classes/subscriber/Optimization/class-critical-css-subscriber.php

In 3.4.3 the CDN feature is not rewriting asset paths in critical path CSS due to high priority in here:
https://github.com/wp-media/wp-rocket/blob/master/inc/classes/subscriber/Optimization/class-critical-css-subscriber.php#L46

Fix #2217 CDN + Optimize CSS delivery - assets are not rewritten because of priority

---

inc/functions/files.php

Fixes:
`Notice: Use of undefined constant WP_ROCKET_CONFIG_PATH - assumed 'WP_ROCKET_CONFIG_PATH' in /home/alfonsoc/public_html/rocket/wp-content/plugins/wp-rocket/inc/classes/logger/class-logger.php on line 236`
```
-- | -- | -- | -- | --
1 | 0.0042 | 435704 | {main}( ) | .../index.php:0
2 | 0.0088 | 479232 | require_once( '/app/public/wp-admin/admin.php' ) | .../index.php:10
3 | 0.0110 | 493856 | require_once( '/app/public/wp-load.php' ) | .../admin.php:34
4 | 0.0134 | 505496 | require_once( '/app/public/wp-config.php' ) | .../wp-load.php:37
5 | 0.0163 | 591072 | require_once( '/app/public/wp-settings.php' ) | .../wp-config.php:109
6 | 0.0622 | 1367712 | include( '/app/public/wp-content/advanced-cache.php' ) | .../wp-settings.php:95
7 | 0.0964 | 1699928 | …
```

Fix undefined constant WP_ROCKET_CONFIG_PATH

---

inc/classes/subscriber/Cache/PurgeActionsSubscriber.php

deleted_user is too late, the user was already deleted, preventing the user ID from being accessed, and the cache directory form being removed.

Update hook name to delete_user

---

.gitignore
tests/Integration/TestCase.php
tests/Unit/TestCase.php

Adds the ability to load private API credentials from:
- local machine's env var
- local machine's config file, i.e. located in `tests/env/local/`.
- via Travis in an encrypted env var

Add API Credential Handling to Tests.

---

.travis.yml

Why? Speed up the builds.
What about version differences?
We are not using the new PHP 7 features. For us, there's no difference between PHP 7.0, 7.1, or 7.2. In other words, the builds on 7.0 and 7.1 are redundant and unnecessary for us.
Note:
This change has no impact on the product or our customers. This impacts dev only.

Optimize Travis by removing PHP 7.0 and 7.1 builds

---

.gitignore
.travis.yml
tests/Integration/TestCase.php
tests/Unit/TestCase.php
tests/Unit/bootstrap.php

`Fatal error: Cannot redeclare rocket_get_constant() (previously declared in /home/travis/build/wp-media/wp-rocket/vendor/brain/monkey/src/Expectation/FunctionStub.php(52) : eval()'d code:2) in /home/travis/build/wp-media/wp-rocket/inc/constants.php on line 32`
Picked from https://github.com/wp-media/wp-rocket/pull/2249/commits/6a5bbe228d0bebc3d1b7685d872653eba6677c1c
This is needed to prevent the error everytime we use `when` or `expect` for `rocket_get_constant` in the unit tests

Load constants.php early to prevent fatal error

---

inc/classes/optimization/JS/class-combine.php

Exclude inline JavaScript keyword to prevent cache directory size issue related to TagDiv Cloud Library: https://cloud.tagdiv.com/#/load/All
See ticket: https://secure.helpscout.net/conversation/1053324383/140499

Exclude inline JavaScript keyword -- cache directory size

---

inc/classes/optimization/CSS/class-critical-css.php

This PR auto-excludes the `attachment_category` taxonomy from CPCSS which is generated by Media Library Assistant.
This taxonomy allows to categorize the media only in the admin. No public URL exist.
Related ticket:
https://secure.helpscout.net/conversation/1042714840/138497?folderId=273768

Auto exclude attachement_category taxonomy from CPCSS

---

inc/classes/subscriber/Optimization/class-lazyload-subscriber.php

The feature is not merged yet in core, but to be ahead, we decide to handle this in the plugin using the provided filter `wp_lazy_loading_enabled`.
We will disable core lazyload when our images lazyload is enabled in WP Rocket settings.

Disable WP 5.4 core lazyload when WPR images lazyload is enabled

---

inc/classes/admin/settings/class-beacon.php

Setting the locale property of the `Beacon` class was creating 2 database queries on every page request (front and back), to get the user and user metadata (by `get_user_locale()`). While the queries were very fast, they were still unnecessary.
To remove them, I moved the setting of the local property to a new private method, and changed the calls to the property to method calls instead.

Remove unnecessary DB queries caused by Beacon class

---

composer.json
composer.lock
tests/Integration/Subscriber/ThirdParty/Plugins/Ecommerce/WooCommerce/TestNonceUserLoggedOut.php
tests/Integration/bootstrap.php
tests/Integration/init-tests.php
tests/Integration/phpunit.xml.dist
tests/Unit/init-tests.php
tests/Unit/phpunit.xml.dist

This PR does the following:
- Changes the composer test scripts to run `phpunit` directly
- Changes to make Rocket first and then it loads `wp-media/phpunit` bootstrap files
- Solves the integration test database error problem. Credit @crystinutzaa 
- Moves WooCommerce tests to a separate group and composer script

Improves test bootstrapping

---

composer.json
inc/classes/subscriber/CDN/RocketCDN/AdminPageSubscriber.php
inc/classes/subscriber/CDN/RocketCDN/NoticesSubscriber.php
inc/functions/api.php
inc/main.php
tests/Integration/Functions/rocketIsLiveSite.php
tests/Integration/Subscriber/CDN/RocketCDN/AdminPageSubscriber/addSubscriptionModal.php
tests/Integration/Subscriber/CDN/RocketCDN/AdminPageSubscriber/displayManageSubscription.php
tests/Integration/Subscriber/CDN/RocketCDN/AdminPageSubscriber/displayRocketcdnStatus.php
tests/Integration/Subscriber/CDN/RocketCDN/NoticesSubscriber/addDismissScript.php
tests/Integration/Subscriber/CDN/RocketCDN/NoticesSubscriber/displayRocketcdnCta.php
tests/Integration/Subscriber/CDN/RocketCDN/NoticesSubscriber/promoteRocketcdnNotice.php
tests/Unit/Functions/rocketIsLiveSite.php
tests/Unit/Subscriber/CDN/RocketCDN/AdminPageSubscriber/addSubscriptionModal.php
tests/Unit/Subscriber/CDN/RocketCDN/AdminPageSubscriber/displayManageSubscription.php
tests/Unit/Subscriber/CDN/RocketCDN/AdminPageSubscriber/displayRocketcdnStatus.php
tests/Unit/Subscriber/CDN/RocketCDN/NoticesSubscriber/addDismissScript.php
tests/Unit/Subscriber/CDN/RocketCDN/NoticesSubscriber/displayRocketcdnCta.php
tests/Unit/Subscriber/CDN/RocketCDN/NoticesSubscriber/promoteRocketcdnNotice.php
views/settings/rocketcdn/dashboard-status.php

We don't want users to signup for RocketCDN on localhost or staging sites. This PR adds:
- a function `rocket_is_live_site()` to check if the current URL corresponds to localhost or known staging domains
- Checks in method displaying content related to RocketCDN on the settings page
- Updated unit & integration tests
**To-Do**

Hide RocketCDN on local/staging sites

---

inc/admin/ui/enqueue.php
inc/classes/subscriber/CDN/RocketCDN/AdminPageSubscriber.php
tests/Integration/Subscriber/CDN/RocketCDN/AdminPageSubscriber/addSubscriptionModal.php
tests/Unit/Subscriber/CDN/RocketCDN/AdminPageSubscriber/addSubscriptionModal.php

Remove the use of the dave site for RocketCDN when `WP_ROCKET_DEBUG` is enabled

Remove RocketCDN debug to dave

---

inc/admin/ui/enqueue.php

`WP_ROCKET_WEB_MAIN` value is `https://wp-rocket.me/`, and the iframe origin is `https://wp-rocket.me`. This was causing an issue in the Javascript because the 2 didn't exactly match.

Remove trailingslash before sending data

---

inc/functions/api.php
tests/Integration/Functions/rocketIsLiveSite.php
tests/Unit/Functions/rocketIsLiveSite.php

This PR adds a filter `'rocket_tld_is_live_prod_site'` for `.dev` and `.dev.cc` TLDs. 
- By default, these TLDs are considered development purposes only. 
- A customer or dev can register a `__return_true` callback to indicate that their `.dev` or `.dev.cc` TLD is the real live PROD website (and not for local or development site).
Why? We currently have over 4,500 customers with dev TLDs. This filter gives them a way to use RocketCDN.

Adds a filter to rocket_is_live_site() for dev TLDs to be live prod site.

---

inc/classes/Buffer/class-cache.php

If the destination file defined in `move()` already exists, the method bails out early, and the temp file remains.
By using the 3rd parameter, an overwrite of the existing file is forced, preventing the issue.

Overwrite destination cache file if it already exists

---

inc/Addon/Varnish/Varnish.php

After QA testing and discussing with Piotr, we agreed that reverting the default scheme to `http` when doing the Varnish purge request was the best way to go:
- We didn't get many tickets related to this specific topic
- Changing the behaviour could lead to more tickets, as for example Cloudways Varnish uses `http` only even for a website with SSL
- A filter is available to change the scheme if our users need to

Revert to http as default scheme for Varnish request

---

inc/classes/preload/class-abstract-preload.php
inc/classes/preload/class-abstract-process.php
inc/classes/preload/class-full-process.php
inc/classes/preload/class-homepage.php
inc/classes/preload/class-partial-process.php
inc/classes/preload/class-sitemap.php
inc/classes/subscriber/preload/class-preload-subscriber.php
tests/Integration/inc/classes/preload/Full_Process/isMobilePreloadEnabled.php
tests/Integration/inc/classes/preload/Homepage/preload.php
tests/Integration/inc/classes/preload/PreloadTestCase.php
tests/Integration/inc/classes/preload/Sitemap/runPreload.php
tests/Unit/inc/classes/preload/Homepage/preload.php
tests/Unit/inc/classes/preload/Sitemap/runPreload.php

About the way the pages are count:
- Do not count mobile pages.
- Count only pages successfully preloaded (request not blocked internally). We can't know about the request status (200) since the requests are non blocking, we have no answer.
- For the homepage preload, take also the homepage itself into account: since it is requested to grab its URLs, it is preloaded at the same time.
- Use 2 transients for each "source" (mobile and sitemap): this prevents the second source to reset the previous source’s count. So there is no `'rocket_preload_running'` transient anymore, but 2: `'rocket_homepage_preload_running'` and `'rocket_sitemap_preload_running'`. The admin notice shows the addition of both. Note: we could use a single transient containing an array of counts, but async calls + same …

Fix the number of preloaded pages in the admin notice

---

inc/functions/api.php
tests/Integration/Functions/rocketIsLiveSite.php
tests/Unit/Functions/rocketIsLiveSite.php

- Reverts the filter, as it's not needed, per PR #2339.
- Allows `.dev`TLD as a real public TLD, i.e. live site.
- Refactors code for readability and performance.
- Adds `.docksal.site`, as it's coming in [1.4.0](https://github.com/docksal/docksal/issues/1215).

Makes .dev a live site. Reverts filter. Adds .docksal.site as local.

---

inc/classes/preload/class-abstract-preload.php
inc/classes/subscriber/preload/class-preload-subscriber.php
inc/common/purge.php

After purging the cache, the homepage is automatically preloaded. Now it is also preloaded for mobile if the separate mobile cache is enabled.
Closes #2349.

Automatic mobile preload after cache purge

---

inc/3rd-party/3rd-party.php
inc/3rd-party/hosting/flywheel.php
inc/3rd-party/hosting/godaddy.php
inc/3rd-party/hosting/kinsta.php
inc/3rd-party/hosting/o2switch.php
inc/3rd-party/hosting/presslabs.php
inc/3rd-party/hosting/savvii.php
inc/3rd-party/hosting/siteground.php
inc/3rd-party/hosting/wp-serveur.php
inc/3rd-party/hosting/wpengine.php

Fixes:
Fatal error: Cannot redeclare rocket_remove_partial_purge_hooks() (previously declared in /wp-content/plugins/wp-rocket/inc/3rd-party/hosting/kinsta.php:107) in /wp-content/plugins/wp-rocket/inc/3rd-party/hosting/presslabs.php on line 72
In this case a function name (`rocket_remove_partial_purge_hooks`) is used in 2 placed and PHP functions defined inside IF conditions are declared at runtime and functions declared outside if conditions are declared at compile time. So the bailout will not work in this case and it worked in the previous version (it was inside if condition).
Solution:
Move the bailout condition before require. 
This will decrease also a little bit the number of files loaded by WP Rocket. 
https://secure.helpscout.net/conversation/1101455078/149590?folderId=3083222 …

Fixed Declared function at compile time, moved bailout condition before require

---

inc/classes/subscriber/Optimization/class-combine-google-fonts-subscriber.php
inc/classes/subscriber/Optimization/class-minify-css-subscriber.php

Combine CSS and Google Fonts need to be inserted after the CPCSS in the page.
Reference:
- [HS Ticket](https://secure.helpscout.net/conversation/1101451982/149588?folderId=273768)
- Related to PR #2239 
Notes on the issue from Slack thread:
>the combined CSS process is happening on priority 26, so after the critical CSS insertion (19), and they both use the <title> as an anchor, so it ends up above instead of below
- test on customer website: changed priority for combined CSS and Google fonts to 16 and 18 respectively, display is correct ✅ 
- did the same test on my local site ✅

Update priorities to prevent wrong insertion order

---

inc/classes/preload/class-abstract-preload.php
inc/classes/preload/class-abstract-process.php
inc/classes/subscriber/preload/class-preload-subscriber.php
tests/Integration/inc/classes/preload/Full_Process/getItemUserAgent.php
tests/Unit/inc/classes/preload/Process/getItemUserAgent.php
tests/Unit/inc/classes/preload/Process/getMobileUserAgentPrefix.php
tests/Unit/inc/classes/subscriber/preload/Preload_Subscriber/maybePreloadMobileHomepage.php

Make the user agent used to preload mobile pages detected as mobile by `wp_is_mobile()`.
We use now a more complex user agent, closer to a real one, that uses `iPhone` (for WPR mobile detect) and `Mobile` (for `wp_is_mobile()`).
Also, this new string is prepended to the custom user agent instead of being happened.
Fixes #2383.

Fixes #2383: Conflict between WP Rocket mobile preload and wp_is_mobile()

---

composer.json
inc/classes/optimization/CSS/class-critical-css.php
inc/classes/subscriber/Optimization/class-critical-css-subscriber.php
tests/Integration/inc/classes/subscriber/Optimization/class-critical-css-subscriber/generateCriticalCssOnActivation.php
tests/Unit/inc/classes/subscriber/Optimization/class-critical-css-subscriber/generateCriticalCssOnActivation.php

The issue is that critical css is saved in the folder /wp-content/cache/critical-css/1, however on a first activation of Critical CSS this folder does not exist, so there will be an error and a return which will not allow to create the critical CSS.
Scope a solution ✅
The solution should be to check before if the folder structure exists otherwise create it and allow to run the process_handler() function.
Closes #2302 
**TODO**

Fixes #2302 CPCSS is not always automatically generated

---

inc/admin/upgrader.php
inc/front/process.php
tests/Integration/inc/admin/rocketNewUpgrade.php
tests/Unit/inc/admin/rocketNewUpgrade.php

- Remove calls to `wp_unslash()`, WP is not fully loaded at that point
- Regenerate the `advanced-cache.php` file on next plugin update
Closes #2376

Fixes 2376 Prevent PHP Fatal Error in process.php

---

composer.json
inc/functions/options.php
tests/Integration/bootstrap.php
tests/Integration/inc/functions/rocketDeleteLicenceDataFile.php
tests/Unit/inc/functions/rocketDeleteLicenceDataFile.php

On multisite we need to preserve the `licence-data.php` file for other sub-sites to be able to validate the license too
Closes #2411

Prevent licence-data.php file deletion on multisite

---

inc/3rd-party/hosting/godaddy.php
inc/main.php
tests/Integration/inc/ThirdParty/thirdParty.php
tests/Integration/inc/rocketActivation.php

Closes #2416 
- Conditions loading the 3rd party hosting files upon plugin activation
- Checks if class and `vip` method exists. If no, bails out.
Recreates PR #2419 to base off of `master` instead of `develop`.

Fixes 2416 By conditioning loading of hosting files upon plugin activation

---

inc/classes/optimization/CSS/class-combine-google-fonts.php
tests/Fixtures/inc/classes/optimization/CSS/Combine_Google_Fonts/optimize.php
tests/Unit/inc/classes/optimization/CSS/Combine_Google_Fonts/optimize.php

Closes #2241 
**Reproduce the problem** ✅ 
Reproduced on local site
Vasilis did a great job alredy at highlighting what was causing this 👍 
We currently stop the process if there is zero or one Google font on the page
There is multiple steps to achieve this:
- Stop the process only if there is no Google fonts on the page
- Add a new condition for the case when there is only one. We don't want to go through the whole parsing and rewriting in this case, we only want to add the display parameter to it. Faster code
- Create a new method to check if the display parameter is already present in the URL
- If no, add it with the `swap` value by default, filtered with the exisiting filter `rocket_combined_google_fonts_display`
- If yes, check …

Fix #2241 - Add display swap param for single Google font

---

wp-rocket.php

Closes #2455 
It's currently not possible to write automated tests for this, so we will be relying on QA test and live test on customers websites to confirm it works as expected.
@arunbasillal @vmanthos @piotrbak If you can check this change on tickets which reported the following problems:
- Errors in the log related to wp-filesystem, like `ftp_pwd()` related
- License validation issues where email & api key fields are blank

Prevent errors caused by use of WP_Filesystem() for license-data.php require

---

inc/classes/admin/settings/class-settings.php
tests/Fixtures/inc/classes/admin/settings/Settings/sanitizeCallback.php

Closes #2468.
The root cause is related to the order of the operations on this line:
https://github.com/wp-media/wp-rocket/blob/26e4ef22eb690577b5c46f180927af8e6e807742/inc/classes/admin/settings/class-settings.php#L315
The solution will be to first remove the <style> </style> tags and then to run wp_strip_all_tags:
`$input['critical_css'] = ! empty( $input['critical_css'] ) ? wp_strip_all_tags( str_replace( [ '<style>', '</style>' ], '', $input['critical_css'] ), [ "\'", '\"' ] ) : '';`
**Estimate the effort** ✅ 
Effort [XS]

Fix #2464 - CPCSS Allow <style> tag in fallback input field

---

inc/Engine/Preload/PartialPreloadSubscriber.php
tests/Fixtures/inc/Engine/Preload/PartialProcess_Wrapper.php
tests/Integration/inc/Engine/Preload/PartialPreloadSubscriber/maybeDispatch.php
tests/Unit/inc/Engine/Preload/PartialPreloadSubscriber/maybeDispatch.php

This allows to preload (also) the mobile version of the URLs after:
- clearing a post cache,
- clearing a term cache,
- clearing automatically expired cache files.
Closes #2399.

Closes #2399: Partial Preloading doesn't create a mobile file

---

.travis.yml
tests/Integration/bootstrap.php

Fixes the integration bootstrap by removing the duplicate constant definitions.
Fixes Travis by first checking if the `composer.lock` file exists. If yes, remove it.
No QA is needed for this one, as no source code is changed.

Fixes integration bootstrap and travis

---

tests/Fixtures/SitePress.php
tests/Unit/inc/Addon/Varnish/Subscriber/cleanHome.php
tests/Unit/inc/classes/Cache/Expired_Cache_Purge/purgeExpiredFiles.php
tests/Unit/inc/functions/rocketHasI18n.php

Adds unit tests for `rocket_has_i18n()`.
No source code changes. No QA is needed.

Adds unit tests for rocket_has_i18n().

---

composer.json
inc/functions/options.php
tests/Fixtures/inc/functions/rocketIsPluginActive.php
tests/Fixtures/inc/functions/rocketIsPluginActiveForNetwork.php
tests/Integration/inc/functions/rocketIsPluginActive.php
tests/Integration/inc/functions/rocketIsPluginActiveForNetwork.php
tests/Unit/inc/functions/rocketIsPluginActive.php
tests/Unit/inc/functions/rocketIsPluginActiveForNetwork.php

Adds unit and integration tests for both `rocket_is_plugin_active()` and `rocket_is_plugin_active_for_network()`.
Additional changes:
- Adds `@return` to the functions' DocBlocks
- Minor micro-optimizations
- Minor reformatting
- Excludes the `Multisite` group from the `test-integration` script

Tests: Adds tests for rocket_is_plugin_active() and rocket_is_plugin_active_for_network()

---

tests/Fixtures/inc/functions/getRocketOption.php
tests/Integration/inc/functions/getRocketOption.php

Adds integration tests to get_rocket_option().
As the function instantiates objects within it, it is not capable of having unit tests.
No QA is required as the source code is not changed.

Tests: Adds integration tests to get_rocket_option().

---

inc/Addon/Cloudflare/APIClient.php
inc/Addon/Cloudflare/Cloudflare.php
inc/Addon/Cloudflare/composer.json

Fix: #2369 - PHP Notice: Undefined property: stdClass::$error in wp-rocket\inc\Addon\Cloudflare\Cloudflare.php on line 131
Changes Cloudflare API requests from curl to wp_remote_get().
Includes the latest package of WP-Media/Cloudflare which includes = Save development mode and optimal settings when CF credentials are valid.
TO DO

Fix #2369 Cloudflare Addon change curl to wp-remote-get

---

inc/ThirdParty/Plugins/Optimization/AMP.php
tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/isAmpCompatibleCallback.php
tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/isAmpCompatibleCallback.php

AMP plugin compatibility with Reader Mode.
It seems that in Reader Mode  I have URLs with /amp/ for posts, but URLs with ?amp for the rest.

Fix #2216 - Add Reader mode in query strings to provide compatibility with AMP

---

inc/functions/formatting.php
tests/Fixtures/inc/functions/getRocketParseUrl.php
tests/Integration/inc/functions/getRocketParseUrl.php
tests/Unit/inc/functions/getRocketParseUrl.php

- Adds tests for `get_rocket_parse_url()`.
- And ensures the filtered value is always an array data type. Why? We can't trust that callbacks will return an array.

Tests: Adds tests for get_rocket_parse_url().

---

inc/classes/subscriber/Optimization/class-critical-css-subscriber.php
tests/Fixtures/inc/classes/subscriber/Optimization/class-critical-css-subscriber/generateCriticalCssOnActivation.php
tests/Integration/inc/classes/subscriber/Optimization/class-critical-css-subscriber/generateCriticalCssOnActivation.php
tests/Unit/inc/classes/subscriber/Optimization/class-critical-css-subscriber/generateCriticalCssOnActivation.php

- Adds and improves tests for `WP_Rocket\Subscriber\Optimization\Critical_CSS_Subscriber::generate_critical_css_on_activation`.
- Defines `Critical_CSS_Subscriber ` properties (which are assigned in `__construct()`).
QA is not required for this PR.

Tests: Adds and improves tests for WP_Rocket\Subscriber\Optimization\Critical_CSS_Subscriber::generate_critical_css_on_activation

---

inc/functions/files.php
tests/Fixtures/inc/functions/rocketRrmdir.php
tests/Integration/FilesystemTestCase.php
tests/Integration/inc/functions/rocketRrmdir.php
tests/Unit/FilesystemTestCase.php
tests/Unit/inc/functions/rocketRrmdir.php

`rocket_rrmdir()` is an original filesystem function that has not been optimized nor does it have tests. This PR gives it some love as it's a critical part of Rocket.
This PR does the following:
- 🏁 Adds tests
- 🚀 Optimizes by calling `rocket_direct_filesystem()` 1x instead of 11x
- 🚀 Checks if the given directory is in the list of preserves _before_ doing anything else
- 🚀 Optimizes the check for directory in preserves list
- 🏁 Replaces `glob()` with SPL
👉 Needed to move PR #2510 forward.

rocket rrmdir() - Optimizes, replaces glob, and provides full code coverage

---

tests/Integration/ApiTestCase.php
tests/Integration/RESTVfsTestCase.php

Switches to use the new version of `wp-media/phpunit`:
- Adds `RESTVfsTestCase` for Rocket integration tests to use
- Changes the `ApiTestCase` to use the new `WPMedia\PHPUnit\Integration\RESTfulTestCase::doRestPut()` method

Tests: Switches to use wp-media/phpunit v1.1.6

---

inc/functions/files.php
tests/Fixtures/inc/functions/rocketRrmdir.php
tests/Integration/inc/functions/rocketMkdirP.php
tests/Integration/inc/functions/rocketRrmdir.php
tests/Unit/inc/functions/rocketMkdirP.php
tests/Unit/inc/functions/rocketRrmdir.php

PR #2522 broke the check for directories to preserve. How? The directories include regex pattern. For example, PR 2522 did not process:
```
[
'vfs://public/wp-content/cache/wp-rocket/example.org(.*)/fr',
'vfs://public/wp-content/cache/wp-rocket/example.org(.*)/de',
]
```
This PR does the following:
- Converts the array of directories to preserve into an OR string and then escapes the `/` for regex
- Adds a private internal function for checking if the given file/dir should be preserved or not
- Uses the original code as a guide

Fixes `rocket rrmdir` directories to preserve checks

---

tests/Fixtures/inc/ThirdParty/Plugins/Optimization/AMP/isAmpCompatibleCallback.php
tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/TestCase.php
tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/isAmpCompatibleCallback.php
tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/isAmpCompatibleCallback.php

The AMP integration tests are failing due to `rocket_generate_config_file()` expectations. This function is called when the AMP options are updated. However, that doesn't happen when the filter `'rocket_cache_query_strings'` is fired.
This PR:
- removes the `rocket_generate_config_file()` assertion
- moves the test data to fixture
No QA is required as the source code remains untouched.
Errors prior to this PR:
```
"vendor/bin/phpunit" --testsuite integration --colors=always --configuration tests/Integration/phpunit.xml.dist --group WithAmp
Installing...
Running as single site... To run multisite, use -c tests/phpunit/multisite.xml
Not running ajax tests. To execute these, use --group ajax.
Not running ms-files tests. To execute these, use --group ms-files.
Not running external-http tests. …
```

Fixes AMP::is_amp_compatible_callback() tests.

---

inc/common/purge.php
tests/Fixtures/inc/common/rocketWidgetUpdateCallback.php
tests/Integration/inc/common/rocketWidgetUpdateCallback.php
tests/Unit/inc/common/rocketWidgetUpdateCallback.php

Adds integration and unit tests for `rocket_widget_update_callback()` in the `purge.file`. 
No QA is needed, as the source code is not touched in this PR.

Tests: rocket_widget_update_callback()

---

inc/functions/formatting.php
tests/Fixtures/inc/functions/rocketAddUrlProtocol.php
tests/Integration/inc/functions/rocketAddUrlProtocol.php
tests/Unit/inc/functions/rocketAddUrlProtocol.php

`rocket_add_url_protocol()`:
- Adds unit tests
- Adds integration tests
- Optimizes by:
- flipping http/https checks into guard clause
- returning URL from `set_url_scheme()` instead of assigning to variable and then returning
Tests were done _before_ the code was optimized to ensure the changes did not change the behavior.

Tests and optimizes: rocket_add_url_protocol()

---

inc/functions/files.php
tests/Fixtures/inc/functions/rocketCleanMinify.php
tests/Fixtures/inc/functions/rocketRrmdir.php
tests/Fixtures/vfs-structure/default.php
tests/Integration/FilesystemTestCase.php
tests/Integration/inc/functions/rocketCleanMinify.php
tests/Unit/FilesystemTestCase.php
tests/Unit/inc/functions/rocketCleanMinify.php

It's possible for a given extension to be part of the absolute path to the minify cache directory. For example, it could be part of the user account or domain name, such as `kb.css.example.org` or account name `foo.css`. As we learned in PR #2571, we need to prefix the regex with absolute path to the `cache/min` directory to avoid the potential risk of this problem.
In addition, this PR:
- Optimizes the function:
- Bails out if there's no extension to clean
- Calls `rocket_direct_filesystem()` 1x instead of 5x
- Only updates the extensions variable if a string was passed into the function
- Makes it consistent with the other clean functions
- Makes the tests consistent with the other clean functions
- Adds unit tests

Fixes regex and optimizes rocket_clean_minify()

---

inc/functions/files.php
tests/Fixtures/inc/functions/getRocketAdvancedCacheFile.php
tests/Integration/inc/functions/getRocketAdvancedCacheFile.php
tests/Unit/inc/functions/getRocketAdvancedCacheFile.php

- Adds tests for `get_rocket_advanced_cache_file()`
- Micro-optimization: returns filtered content instead of assigning to variable and then returning
- Adds `rocket_get_constant()` to constants to make code testable

Tests: get_rocket_advanced_cache_file()

---

inc/Engine/Optimization/Minify/JS/Combine.php

This PR does an automatic compatibility with FeedbackCompany widget by auto-excluding the JS file and inline JS from our combine JS process.

Auto-exclude FeedbackCompany JS file

---

inc/functions/files.php
tests/Fixtures/inc/functions/rocketGetFilesystemPerms.php
tests/Unit/inc/functions/rocketGetFilesystemPerms.php
tests/VirtualFilesystemTrait.php

- Adds unit tests for `rocket_get_filesystem_perms()`
- Adds `rocket_get_constant()` to make the code testable
- Resets  the static variable to an empty array when testing
- Micro-optimization by switching to if/else instead of `switch/case/breaks` - with only 2 possibilities, if/else is faster and else code

Tests: rocket_get_filesystem_perms()

---

inc/deprecated/3.5.php

This PR fixes the `class_alias` declarations in the 3.5 deprecated file. Why? The arguments are backwards and should be:
```php
class_alias( 'the original class', 'the new class' );
```
[See the PHP manual](https://www.php.net/manual/en/function.class-alias.php).

Fixes the 3.5 deprecated class aliases, i.e. backwards.

---

inc/deprecated/3.5.php

Fixes my mistake in PR #2596 for 3.5 deprecated file:
- restores the `class_alias()` arguments. Doh.
- orders the `class_alias()` lines alphabetically to make it easier to find the one you are looking for.

Restores class_alias arguments order in 3.5 deprecated

---

tests/Fixtures/content/advancedCacheContent.php
tests/Fixtures/inc/functions/getRocketAdvancedCacheFile.php
tests/Fixtures/inc/functions/rocketGenerateAdvancedCacheFile.php
tests/Fixtures/vfs-structure/default.php
tests/Integration/inc/functions/getRocketAdvancedCacheFile.php
tests/Unit/inc/functions/getRocketAdvancedCacheFile.php
tests/Unit/inc/functions/rocketGenerateAdvancedCacheFile.php
tests/Unit/inc/functions/rocketGetFilesystemPerms.php
tests/VirtualFilesystemTrait.php

Improves the virtual filesystem fixtures and tests by:
- Adds ability to pass in the root directory, which allows us to run it  more than once with different directories.
- Adds more constants to the Trait's `getConstant()`
- Uses the Trait's `whenRocketGetConstant()` for `rocket_get_constant()` in the advanced cache tests, i.e. instead of individual expects
- Moves the advanced cache content file to a new `Fixtures\content\` folder for sharing/reuse in the test data
- Adds the different string combinations to the advanced cache content file, i.e. instead of doing it in the test data. Why? Makes it easier and more consistent
- Advanced cache tests now use the default vfs structure
Most of these improvements were identified in PR #2507 and are/will be needed as we build more tests.

Improves the virtual filesystem fixtures and tests

---

inc/functions/formatting.php
tests/Fixtures/inc/Engine/Optimization/Minify/CSS/Combine/combine.php
tests/Fixtures/inc/Engine/Optimization/Minify/JS/Subscriber/process.php
tests/Fixtures/inc/Engine/Optimization/QueryString/RemoveSubscriber/remove-query-strings.php
tests/Integration/inc/Engine/Optimization/Minify/CSS/Subscriber/process.php
tests/Integration/inc/Engine/Optimization/Minify/JS/Subscriber/process.php
tests/Integration/inc/Engine/Optimization/QueryString/RemoveSubscriber/process.php
tests/Integration/inc/Engine/Optimization/TestCase.php
tests/VirtualFilesystemTrait.php

The filter was added for testing purposes, but is not longer needed. This PR removes the filter and then updates the tests that were using it.

Removes filter "rocket_wp_content_dir"

---

inc/Engine/Preload/PartialPreloadSubscriber.php
tests/Fixtures/inc/Engine/Preload/PartialPreloadSubscriber/preloadAfterAutomaticCachePurge.php
tests/Integration/inc/Engine/Preload/PartialPreloadSubscriber/preloadAfterAutomaticCachePurge.php
tests/Unit/inc/Engine/Preload/PartialPreloadSubscriber/preloadAfterAutomaticCachePurge.php

Reproduced on mega website.
The root cause is related to `$data['home_path']` which has the missing / at the end, so the str_replace() will have double // .
`home_path` trims the `/` in here:
https://github.com/wp-media/wp-rocket/blob/0bdcd1d0f9897541af2b589731d04af166ba1504/inc/classes/Cache/class-expired-cache-purge.php#L117-L118
The solution is to add back the '/' in `home_path` if the permalink_structure has the trailing slash:
```
$file_path = untrailingslashit( $file_path );
$data['home_path'] = untrailingslashit( $data['home_path'] );
if ( '/' === substr( get_option( 'permalink_structure' ), -1 ) ) {
$file_path .= '/';
$data['home_path'] .= '/';
}
```
**Estimate the effort** ✅ 
Effort [S] - All the …

Closes #2478 Preload fetches wrong WPML Urls

---

inc/Engine/Cache/AdminSubscriber.php
inc/Engine/Cache/ServiceProvider.php
inc/admin/admin.php
inc/classes/class-plugin.php
inc/deprecated/3.5.php
tests/Fixtures/inc/Engine/Cache/AdminSubscriber/addPurgeTermLink.php
tests/Integration/AdminTestCase.php
tests/Integration/inc/Engine/Cache/AdminSubscriber/addPurgeTermLink.php
tests/Integration/inc/Engine/Cache/AdminSubscriber/registerTermsRowAction.php
tests/Unit/inc/Engine/Cache/AdminSubscriber/addPurgeTermLink.php
tests/Unit/inc/Engine/Cache/AdminSubscriber/registerTermsRowAction.php

Fixes #2504 Prevent deprecated notice on WooCommerce terms list pages

---

inc/functions/files.php
tests/Fixtures/inc/functions/rocketCleanFiles.php
tests/Integration/inc/functions/rocketCleanFiles.php
tests/Unit/inc/functions/rocketCleanFiles.php

This PR does the following:
- Redesigns the processing strategy for `rocket_clean_files()` (details below)
- Optimizes its processing by running only the tasks that need to be run, i.e. instead of running them for every given URL.
Results:
- Processing time: `glob()` (<= WPR 3.5.3) === this version with SPL instead of `glob`.
- It also provides scaffolding to further optimize all of the cleaning functionality.
The previous design used `glob()` (<= v 3.5.3). In WPR 3.5.4, we replaced `glob` with SPL `RegexIterator`. Both of these approaches crawl the filesystem using a wildcard or regex. Why? We need to grab the domain + any user caches for the given URLs to be cleaned. 
For example, let's say the domain is `example.org` and there are 3 user caches for this domain. The cache structure …

Fix #2618 for rocket_clean_files() by running RegexIterator once.

---

inc/Engine/CDN/RocketCDN/CDNOptionsManager.php
tests/Fixtures/inc/Engine/CDN/RocketCDN/CDNOptionsManager/enable_disable.php
tests/Integration/inc/Engine/CDN/RocketCDN/CDNOptionsManager/disable.php
tests/Integration/inc/Engine/CDN/RocketCDN/CDNOptionsManager/enable.php
tests/Unit/inc/Engine/CDN/RocketCDN/CDNOptionsManager/disable.php
tests/Unit/inc/Engine/CDN/RocketCDN/CDNOptionsManager/enable.php

**Describe the bug**
RocketCDN Rest API endpoints do not refresh WP Rocket cache while activating / deactivating RocketCDN. At disable the website will be broken because it still have the CDN URL in the cache files.
**Reproduce the problem** ✅ 
Issue reproduced
it’s not auto-cleaning here because the callback function that does it in a regular context (ie from WP Rocket settings page), is only loaded when is_admin() is true, which won’t be for a REST request.
Add a call to `rocket_clean_domain()` in the enable/disable callbacks methods of `CDNOptionsManager`
**Estimate the effort** ✅ 
Effort [S]
**Backlog Grooming**
TO DO:

Closes #2471 - Clean WP Rocket cache when RocketCDN REST Endpoints are called

---

inc/Engine/Preload/PartialPreloadSubscriber.php

The [Better Notifications for WP](https://wordpress.org/plugins/bnfw/) plugin sends each email notification twice when WP Rocket's preload feature is enabled.
Both plugins are hooking to the shutdown action:
https://github.com/jackmcconnell/bnfw/blob/8560dc81d33b17418aadf06abeed33a7a4fa4e19/bnfw.php#L207
https://github.com/wp-media/wp-rocket/blob/adab7a846f85e1edbdeb7e6a63575789d0f0bf7b/inc/Engine/Preload/PartialPreloadSubscriber.php#L72
Identified this issue on Vasilis test website.
https://github.com/wp-media/wp-rocket/blob/adab7a846f85e1edbdeb7e6a63575789d0f0bf7b/inc/Engine/Preload/PartialPreloadSubscriber.php#L72
The issue is that both plugins run on shutdown action and this may end up in conflict. 
The …

Closes #2620 - BNFW plugin - Duplicate emails are send when preload is enabled

---

inc/functions/files.php
tests/Fixtures/inc/functions/_rocketGetCacheDirs.php
tests/Unit/inc/functions/_rocketGetCacheDirs.php

This PR fixes #2633 by:
1. Checking if it's a Windows-based machine, i.e. via the constant `DIRECTORY_SEPARATOR`.
2. If yes:
- Changes `/` into `\` for the `FilesystemIterator`
- Prepares the directory separator for regex.
Note: Skips this switching code when using the virtual filesystem.

Fixes 2633: RegexIterator regex to use Windows dir separator when IIS/Windows

---

composer.json

Package needs to stays to version 2.5.6 for now because of https://github.com/wp-media/wp-rocket/issues/2570
We will be able to revert this change when releasing version 3.6.

Prevent update of rocket-lazyload-common package

---

inc/Engine/Optimization/GoogleFonts/Combine.php
tests/Fixtures/inc/Engine/Optimization/GoogleFonts/Combine/optimize.php

When a Google font is used in Jetmenu settings, and Combine Google Fonts is enabled at WP Rocket, JetMenu will add its own google font tag. If the theme already has another google font tag, the combined file will get injected twice at the HTML, the usual injection and another one inside JetMenu data-menu-options object, breaking the menu functionality.
Identified this issue on localhost.
The root cause is that JetMenu contains SVG which contains `<title></title>` and Google Fonts is appended after `</title>` in here:
https://github.com/wp-media/wp-rocket/blob/57003cff362df710d36acb49085115ea4d09e0eb/inc/Engine/Optimization/GoogleFonts/Combine.php#L79
I would go on targeting with regex </title> withing …

Closes #2561 Combine Google Fonts and JetMenu incompatibility

---

inc/Engine/Cache/PurgeActionsSubscriber.php
tests/Fixtures/inc/Engine/Cache/PurgeActionsSubscriber/maybePurgeCacheOnTermChange.php
tests/Integration/inc/Engine/Cache/PurgeActionsSubscriber/maybePurgeCacheOnTermChange.php

`PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function WP_Rocket\Engine\Cache\PurgeActionsSubscriber::maybe_purge_cache_on_term_change(), 2 passed in /home/aswakdriwr/delivery/wp-includes/class-wp-hook.`
This happens because `pre_delete_terms` uses 2 arguments only. I used this hook at the start of the work on the PR, then noticed I could use `delete_term` instead, and forgot to update the hook name in `get_subscribed_events()`.
The error wasn't reported during QA.

Hotfix: Prevent PHP fatal error when trying to delete a term

---

inc/Engine/CriticalPath/AdminSubscriber.php
tests/Fixtures/inc/Engine/CriticalPath/AdminSubscriber/enqueueAdminEditScript.php
tests/Integration/inc/Engine/CriticalPath/AdminSubscriber/enqueueAdminEditScript.php
tests/Unit/inc/Engine/CriticalPath/AdminSubscriber/enqueueAdminEditScript.php

Following what Arun found during QA here: https://github.com/wp-media/wp-rocket/pull/2652#issuecomment-632240496
```
[21-May-2020 17:28:37 UTC] PHP Notice:  Trying to get property 'post_status' of non-object in /app/public/wp-content/plugins/wp-rocket/inc/Engine/CriticalPath/AdminSubscriber.php on line 220
[21-May-2020 17:28:37 UTC] PHP Stack trace:
[21-May-2020 17:28:37 UTC] PHP   6. WP_Rocket\Engine\CriticalPath\AdminSubscriber->enqueue_admin_edit_script() /app/public/wp-includes/class-wp-hook.php:287
[21-May-2020 17:28:37 UTC] PHP   7. WP_Rocket\Engine\CriticalPath\AdminSubscriber->is_enabled() /app/public/wp-content/plugins/wp-rocket/inc/Engine/CriticalPath/AdminSubscriber.php:89
[21-May-2020 17:28:37 UTC] PHP   8. WP_Rocket\Engine\CriticalPath\AdminSubscriber->get_disabled_data() …
```

Fixes PHP notice on posts list page

---

inc/Engine/CriticalPath/CriticalCSSSubscriber.php

Solve the issue of checking critical css folder that has any files to bailout and stop generation.

Correctly generate CPCSS on Optimize CSS delivery activation

---

inc/Engine/Preload/PartialPreloadSubscriber.php
tests/Fixtures/inc/Engine/Preload/PartialPreloadSubscriber/preloadAfterAutomaticCachePurge.php

**Describe the bug**
In 3.5.5 version we fixed the problem with expired cache preload for WPML. In this fix, we introduced another problem. When `$data['home_url']` doesn't contain `/`:
https://github.com/wp-media/wp-rocket/blob/c7a020448d6639ca3cb4cddf72195f9d9c18fbec/inc/Engine/Preload/PartialPreloadSubscriber.php#L151
We're not preloading the expired cache.
**To Reproduce**
Steps to reproduce the behavior:
1. Go to the WordPress site without WPML and other plugins manipulating home_url
2. Set Cache Lifespan to 10 minutes
3. Preload cache manually
4. Confirm that the expired cache is not preloaded
**Expected behavior**
We need to preload expired cache correctly
**Additional context**
The solution would be to make an additional check and append `/` if it's missing: …

Closes #2665 - Expired cache preload doesn't fetch the correct URLs

---

inc/Engine/CriticalPath/Admin/Subscriber.php
inc/common/admin-bar.php

Add new hook `rocket_admin_bar_items` to preserve the order of the sub-items in the WP Rocket admin bar menu.

Update WP Rocket admin bar items order

---

inc/admin/admin.php

The type cast of the argument to an array was causing a fatal error when dismissing a notice.
This was added in changes we made in 3.6, so it doesn't affect any of our users.
To be honest, I'm not sure why the argument exists in the first place, this method is a callback for admin-ajax/admin-post, so it should not expect any argument directly. This code is 6 years old so who knows.
I also removed a reference to `__rocket_imagify_notice` which is not used in the plugin anymore since 3.2.
I did the QA on this change myself.

Prevent fatal error when trying to dismiss a notice

---

inc/Engine/CriticalPath/CriticalCSSSubscriber.php

- Check for `total` transient index before using it in the notice

Prevent PHP notice in CPCSS running notice

---

inc/Engine/Cache/AdvancedCache.php
tests/Fixtures/inc/Engine/Cache/AdvancedCache/noticeContentNotOurs.php
tests/Integration/inc/Engine/Cache/AdvancedCache/noticeContentNotOurs.php
tests/Unit/inc/Engine/Cache/AdvancedCache/noticeContentNotOurs.php

Closes #2721 
- Add check for `WP_CACHE` before displaying this notice
- Update tests

Prevent false positive notice "content not ours" after license validation

---

inc/ThirdParty/Plugins/Optimization/AMP.php
tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php
tests/Integration/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmpWithCloudflare.php
tests/Unit/inc/ThirdParty/Plugins/Optimization/AMP/disableOptionsOnAmp.php

Fixes #2523
The issue is happening because lazyload for images is disabled on AMP pages, but not lazyload for iframes. So the inline CSS fallback is still inserted on the pages.

Fixes #2523 Prevent lazyload inline CSS insertion on AMP pages

---

inc/Engine/CriticalPath/RESTWP.php
tests/Fixtures/inc/Engine/CriticalPath/RESTWPPost/delete.php
tests/Fixtures/inc/Engine/CriticalPath/RESTWPPost/generate.php
tests/Integration/inc/Engine/CriticalPath/RESTWPPost/delete.php
tests/Integration/inc/Engine/CriticalPath/RESTWPPost/generate.php
tests/Unit/inc/Engine/CriticalPath/RESTWPPost/delete.php
tests/Unit/inc/Engine/CriticalPath/RESTWPPost/generate.php

This is easy to be reproduces on local.
The root cause is in the `RestWP.php`
https://github.com/wp-media/wp-rocket/blob/1455187900e01a22cc6ec8696511f1df01e18de7/inc/Engine/CriticalPath/RESTWP.php#L112
https://github.com/wp-media/wp-rocket/blob/1455187900e01a22cc6ec8696511f1df01e18de7/inc/Engine/CriticalPath/RESTWP.php#L223
In the initial specs of this one we forgot to include the cleaning of the cache for the specific page for which we regenerate the CPCSS.
The solution is to create a private method in `RESTWP.php` which cleans the cache based on post id. This method can be shared between delete() & generate() functions.
Preloading this page at this point is not an option because the code is already fragile …

Closes #2739 Clean post cache on Specific CPCSS generation or deletion

---

inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php
inc/Engine/Optimization/Minify/JS/Combine.php
tests/Fixtures/inc/Engine/Optimization/Minify/JS/Combine/combine.php
tests/Fixtures/inc/Engine/Optimization/Minify/JS/Subscriber/process.php
tests/Integration/inc/Engine/Optimization/Minify/JS/Subscriber/process.php
tests/Unit/inc/Engine/Optimization/Minify/CSS/Combine/optimize.php
tests/Unit/inc/Engine/Optimization/Minify/CSS/Minify/optimize.php
tests/Unit/inc/Engine/Optimization/Minify/JS/Combine/optimize.php
tests/Unit/inc/Engine/Optimization/Minify/JS/Minify/optimize.php
tests/Unit/inc/Engine/Optimization/TestCase.php

**Reproduce the problem** ✅ 
Reproduced on test installation
In https://github.com/wp-media/wp-rocket/blob/00cf7a1c5e0b2e7354b0aa76ca86603ee4420eae/inc/classes/optimization/JS/class-abstract-js-optimization.php#L145
We only get the URL for the WP core jQuery, not for any externally hosted jQuery like we do for deferred JS.
Improve this method to also exclude known externally hosted jQuery, like from Jetpack, googleapis.com or cdnjs.cloudflare.com
**Effort** ✅ 
Effort `[S]`

Closes #2493 Exclude external jQuery from combine when Defer Safe Mode is active

---

inc/Engine/Optimization/ServiceProvider.php
inc/Plugin.php
inc/deprecated/3.6.php
inc/deprecated/3.7.php
inc/deprecated/subscriber/admin/Optimization/class-minify-html-subscriber.php
inc/deprecated/vendors/classes/class-minify-html.php
inc/main.php

Sub-task for epic #2682 
- Remove the minify_html_subscriber entry from the subscribers
- Deprecate the class
- Remove registering minify HTML subscriber in $provides and register()
- Deprecate the class

Remove minify HTML option: front (1/3)

---

inc/Engine/Admin/Beacon/Beacon.php
inc/Engine/Admin/Deactivation/DeactivationIntent.php
inc/Engine/Admin/Settings/Page.php
inc/Engine/Admin/Settings/Settings.php
inc/admin/ui/meta-boxes.php
inc/admin/ui/notices.php
inc/admin/upgrader.php
tests/Fixtures/inc/admin/rocketFirstInstall.php
tests/Integration/inc/Engine/Admin/Deactivation/DeactivationIntent/activateSafeMode.php
tests/Unit/inc/Engine/Admin/Deactivation/DeactivationIntent/activateSafeMode.php

Sub-task for epic #2682 
- Remove the entry for `minify_html` in `rocket_first_install()`
- Remove the checks for `minify_html` in `rocket_new_upgrade()`
- Remove `minify_html` from the `$fields` in `rocket_display_cache_options_meta_boxes()` and `rocket_save_metabox_options()`
- Remove the checks for `minify_html` in `rocket_plugins_to_deactivate()`
- Remove `minify_html` from `session_data()`
- Remove `minify_html` from `activate_safe_mode()`
- Remove references to minify HTML option
- Remove references to `minify_html` in `sanitize_callback()`
+ Removed from fixture & Unit & Integration test `activateSafeMode.php`

Remove minify HTML option: backend (2/3)

---

tests/Integration/inc/Engine/CDN/RocketCDN/APIClient/getSubscriptionData.php
tests/Integration/inc/Engine/CDN/RocketCDN/APIClient/purgeCacheRequest.php
tests/Integration/inc/Engine/CDN/RocketCDN/TestCase.php

Revisit RocketCDN integration tests and change the home_url() to the new website.

RocketCDN integration tests home_url change

---

inc/functions/options.php
tests/Integration/inc/functions/getRocketExcludeDeferJs.php
tests/Unit/inc/functions/getRocketExcludeDeferJS.php

Closes #2833 
Excluding `widget.reviews.io` pattern from Load JavaScript Deferred

Excluded widget.reviews.io pattern from JS defer

---

inc/Engine/Optimization/Minify/JS/Combine.php

If you're using a gleam.io widget on a website and the combine js feature is enabled the widget will not render. This can be fixed by excluding the JS in the plugin options. (had to do this on a client site basically the widget never renders). This patch simply makes it permanent to save people time and to avoid issues.

Exclude Gleam.io JS From Being Merged

---

inc/Engine/Admin/Settings/Page.php
inc/functions/htaccess.php
inc/functions/options.php
languages/rocket.pot
tests/Fixtures/content/htaccessContent.php

We didn't have many instances of them in our codebase
We still have one instance of `blacklist`, but it's in a conditional coming from an API response, so we need the response updated before we can also update on our side.

Remove/update instances of blacklist/whitelist in the code

---

inc/admin/upgrader.php
tests/Unit/inc/admin/rocketNewUpgrade.php

Sub-task for epic #2791
Closes https://github.com/wp-media/wp-rocket/issues/2799
Call `clean_minify( CSS )` during upgrading from v3.6.x to v3.7 to regenerate all CSS files and apply the new functionality.
Revisit Unit tests to include the new change

Apply font-display: swap in CSS files - On Upgrading to v3.7( 5/5 )

---

tests/Fixtures/inc/Engine/CriticalPath/CriticalCSS/getExcludeAsyncCss.php
tests/Fixtures/inc/Engine/Optimization/IEConditionalSubscriber/extractIeConditionals.php
tests/Fixtures/inc/Engine/Optimization/IEConditionalSubscriber/injectIeConditionals.php
tests/Integration/inc/Engine/CriticalPath/CriticalCSS/getExcludeAsyncCss.php
tests/Integration/inc/Engine/Optimization/IEConditionalSubscriber/TestCase.php
tests/Integration/inc/Engine/Optimization/IEConditionalSubscriber/extractIeConditionals.php
tests/Integration/inc/Engine/Optimization/IEConditionalSubscriber/injectIeConditionals.php
tests/Unit/inc/Engine/CriticalPath/CriticalCSS/getExcludeAsyncCss.php
tests/Unit/inc/Engine/Optimization/IEConditionalSubscriber/TestCase.php
tests/Unit/inc/Engine/Optimization/IEConditionalSubscriber/extractIeConditionals.php
tests/Unit/inc/Engine/Optimization/IEConditionalSubscriber/injectIeConditionals.php

Add back the tests for:
- the `IEConditionalSubscriber` class methods
- The `CriticalCSS::get_exclude_async_css()` method
Those tests were deleted when reverting the async CSS change PR, but they can be preserved as the code related to them was preserved too.

Re-add deleted tests & fixtures related to IEConditionalSubscriber & CriticalCSS

---

inc/common/purge.php
inc/functions/files.php
tests/Fixtures/inc/common/rocketGetPurgeUrls.php
tests/Fixtures/inc/functions/_rocketGetRecursiveDirFilesByRegex.php
tests/Integration/inc/common/rocketGetPurgeUrls.php
tests/Unit/inc/common/rocketGetPurgeUrls.php
tests/Unit/inc/functions/_rocketGetRecursiveDirFilesByRegex.php

Identified the issue on my localhost.
This was never working: RegEx never worked for Always purge URL(s) field though. The code is expecting standard paths.
I made some prototyping / discovery work and this code should work just fine:
```
function get_recursive_dir_files_by_regex( $dir, $regex ) {
try {
$iterator = new RecursiveIteratorIterator(
new RecursiveDirectoryIterator( $dir )
);
return new RegexIterator( $iterator, $regex,  RecursiveRegexIterator::MATCH);
} catch ( Exception $e ) {
return [];
}
}
$files = get_recursive_dir_files_by_regex( WP_CONTENT_DIR . '/cache/wp-rocket/wp.local/' , '/category\/(.*)\/sub-category\/(.*)/i');
```
**Effort** ✅ 
I would assume this will be an [S]. 
TO DO: …

Closes #1523 Wildcards do not work in Always Purge URL(s)

---

inc/Engine/CriticalPath/CriticalCSSSubscriber.php
tests/Fixtures/inc/Engine/CriticalPath/CriticalCSSSubscriber/insertCriticalCssBuffer.php
tests/Fixtures/inc/Engine/CriticalPath/CriticalCSSSubscriber/insertCriticalCssBufferUnit.php

Closes #2828 
- Modifies the `wprRemoveCPCSS` script to check timing for removal of CriticalCSS to make sure all default CSS links have been reset from `preload` to `stylesheet`.
- Adds `data-rocket-async="style"` attribute to target preloaded style links.
- Updates relevant `CriticalCSSSubscriber` tests.

Fixes #2828: CriticalCSS removal can cause delayed FOUC in Firefox

---

inc/Engine/Admin/Beacon/Beacon.php
inc/Engine/Admin/Settings/Page.php
inc/Engine/Preload/Links/AdminSubscriber.php
inc/Engine/Preload/Links/ServiceProvider.php
inc/Plugin.php
tests/Fixtures/inc/Engine/Preload/Links/AdminSubscriber/addOption.php
tests/Fixtures/inc/admin/rocketFirstInstall.php
tests/Integration/inc/Engine/CriticalPath/Admin/Subscriber/addAsyncCssMobileOption.php
tests/Integration/inc/Engine/Preload/Links/AdminSubscriber/addOption.php
tests/Unit/inc/Engine/Preload/Links/AdminSubscriber/addOption.php

Closes #2900, first sub-task of the epic.
This part adds the new Preload Links option to the UI of WP Rocket settings page, and add the option index `preload_links` to the WPR options array.

Closes #2900: Preload links: admin part (1/3)

---

gulpfile.js
package.json

Breaking this PR out of the delay JS feature branch as it's also needed for Prefetch Pages script.
This new Gulp task allows us to compile a single `assets/js/` script by:
- Running babel to transpile modern JS back into older ES5 version for wider browser compatibility
- Running uglify to minify the script
- Renaming the new compiled script to `.min.js`

Add Gulp task for compiling a single JS script

---

tests/Integration/inc/classes/subscriber/Optimization/Dequeue_JQuery_Migrate_Subscriber/dequeueJqueryMigrate.php

fixes #2990 
Wordpress from version 5.5 stopped support for jquery-migrate script out of the box so we need to adjust the code/tests to check the wordpress version if greater than or equals 5.5 so do the followings:-
Adjust the tests not to expect this script to be returned from WP.

Adjust tests not to support jquery-migrate after WP version 5.5

---

inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php

The `$wp` global is not created yet on `plugins_loaded`, which was triggering the following notices:
```
PHP Notice:  Trying to get property 'query_vars' of non-object
PHP Notice:  Trying to get property 'request' of non-object
```
Changing the hook to `after_setup_theme` solves the issue, at that point the global is populated with the necessary object.

Prevent PHP notice when trying to serve the WC empty cart cache

---

inc/Engine/Optimization/GoogleFonts/Combine.php
tests/Integration/inc/Engine/Optimization/GoogleFonts/Combine/optimize.php
tests/Unit/inc/Engine/Optimization/GoogleFonts/Combine/optimize.php

Fixes #2962 
The current regEx used was causing a catastrophic backtracking fatal error when the content inside the `<head>` was too big.
This PR changes the regEx to a simpler expression, similar to the one used for combine CSS or inserting the critical CSS.

Fixes #2962 Prevent whitescreen when Optimizing Google Fonts in some cases

---

inc/Engine/Preload/Links/Subscriber.php

Adds a filter `rocket_preload_links_config` to provide access for developers to tune the feature for their specific website.
Why?
Request from Product - to provide tuning and discovery on customer websites.
Tested on our dev sites:

Adds filter for Preload Links script configuration parameters.

---

inc/Engine/Optimization/Minify/CSS/Combine.php

An external URL without protocol (starting with `//`), including `url()` inside, caused the paths rewritting inside of it to be incorrect.
This PR fixes the issue by setting the protocol on the external URL earlier.

Add protocol early to external URL to prevent incorrect rewriting paths during combine CSS

---

inc/Engine/Preload/Links/Subscriber.php

Reverts the tiny change I did yesterday when adding the configuration filter:
- reverts the `usesTrailingSlash` parameter back to boolean (from int).
Why?
The script expects this format (doh). It uses this to know whether to add or not add the trailingslash. Without it, it causes retries when prefetching  - not what we want.
This change has already been QA'd by @Davidacu through the extensive Preload Links QA/testing. One of those last minute changes that bite me in the backside. Doh.
Tested and working again on https://wp-rocket.dev/.
👉  No QA is needed for this PR as it reverts it back to what David already tested.

Reverts `usesTrailingSlash` config for Preload Links

---

inc/Engine/Optimization/Minify/JS/Combine.php

Tickets:
- https://secure.helpscout.net/conversation/1260607059/189022/
- https://secure.helpscout.net/conversation/1249427807/185531/
- https://secure.helpscout.net/conversation/1248829743/185389/

Exclude inline JavaScript keywords to prevent the cache dir size issue

---

inc/deprecated/3.7.php

After discussions, we decided to wrap the deprecated classes with `class_exist` to avoid loading when the class already exists in memory.
Closes #3047

Fixes 3047 - Guards deprecated Minify_HTML class to avoid fatal errors.

---

inc/deprecated/3.7.php

Prevent a PHP warning in 3.7:
`Warning: Cannot declare class \ Rocket_Mobile_Detect, because the name is already in use in plugins/wp-rocket/ inc / deprecated / 3.7.php on line 12`
The class alias is not necessary as the class is still present in the codebase.
Closes #3052

Remove class alias for Rocket_Mobile_Detect

---

inc/Engine/Optimization/Minify/JS/Combine.php

This PR will automatically exclude our Preload and Delay JS inline scripts. It will ensure us that these features will always work. By being included into the combined JS files, our features can stop to work if a JS error is triggered.
Slack conversation: https://wp-media.slack.com/archives/GUT7FLHF1/p1599831075030100

Auto exclude preload delay js scripts

---

inc/functions/htaccess.php

Closes #2879 
Update `get_rocket_htaccess_mod_expires()` function to change the browser cache expiration for `ogg`, `mp4` and `webm` to 4 months instead of one. This is to improve results in PageSpeed Insights tests.

Closes #2879 Set browser cache expiration to 4 months for videos/audios files

---

inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php
inc/functions/formatting.php
tests/Fixtures/inc/Engine/Optimization/Minify/JS/Combine/combine.php
tests/Unit/inc/Engine/Optimization/Minify/JS/Combine/optimize.php

Fixes #2846 
Instead of directly using the value from the `src` property for jQuery, we check if the `host` is set for it. If not, we call `site_url()` to make sure we get the absolute URL for the file, and then keep only the path.
This is reverting to how we did it previously.

Fixes #2846 Correctly exclude jQuery from combine when WP is in a subfolder

---

inc/Engine/Optimization/DelayJS/HTML.php

The single line flag `s` is required to match inline JS content containing new lines.

Fixes #3109 Add back the single line flag for inline JS content match in delay JS

---

inc/Engine/Optimization/Minify/JS/Combine.php

This prevents it from being combined if the theme is not supporting the `html5` argument in its config.

Fixes #3100 Exclude RocketPreloadLinksConfig from combine JS

---

composer.json

The Cloudflare module PSR-4 is not in the main composer.json file, which is preventing the classes from being added to the autoloader, and causing a fatal error when the addon is activated.

Fixes PHP Fatal error in 3.7.1 because of missing autoload for Cloudflare module

---

inc/Engine/Preload/Links/Subscriber.php

Closes #3071 
Changes the `RocketPreloadLinksConfig.siteUrl` config parameter to use `home_url()` instead of `site_url()`. This fixes the problem of when WordPress is in a sub-directory environment (such as when using Bedrock).

Fixes #3071: Preload Links siteUrl configuration for when WordPress is in sub-directory

---

inc/functions/files.php

creating directories without `index.html` file may lead to security hole.

Add index.html inside each directory created by wp rocket

---

inc/functions/api.php

Initial ticket: https://secure.helpscout.net/conversation/1287933357/196396/
Adds .dream.press staging to the list.
Related in part to https://github.com/wp-media/wp-rocket/issues/2789

Adding new staging site

---

inc/functions/options.php
tests/Integration/inc/functions/getRocketExcludeDeferJs.php
tests/Unit/inc/functions/getRocketExcludeDeferJS.php

The aos.js library (https://github.com/michalsnik/aos) is used by  https://oxygenbuilder.com/
When DeferJS is enabled, there is and "AOS is undefined" error on AOS.init, excluding the JS file from deferring solves the issue.
Ticket: https://secure.helpscout.net/conversation/1267928807/190825?folderId=2683093

Excluding aos.js from DeferJS

---

inc/Engine/License/API/PricingClient.php
inc/Engine/License/ServiceProvider.php
inc/Plugin.php
tests/Fixtures/inc/Engine/License/API/PricingClient/getPricingData.php
tests/Integration/inc/Engine/License/API/PricingClient/getPricingData.php
tests/Unit/inc/Engine/License/API/PricingClient/getPricingData.php

Closes #3149 
This class is used to get the pricing data using `get_pricing_data()`
If the data is already cached in a transient `wp_rocket_pricing`, it uses the cached data. Else, it sends a request to the API endpoint, and caches the returned JSON data for 6 hours in the transient.
If an error occurs (`WP_Error`, or response code not `200`), the method returns false.

Closes #3149 PricingClient class to get data from pricing endpoint

---

inc/Engine/License/API/UserClient.php
inc/Engine/License/ServiceProvider.php
inc/Plugin.php
tests/Fixtures/inc/Engine/License/API/UserClient/getUserData.php
tests/Integration/inc/Engine/License/API/UserClient/getUserData.php
tests/Unit/inc/Engine/License/API/UserClient/getUserData.php

Closes #3143 
This class is used to get the user data using `get_user_data()`
If the data is already cached in a transient `wp_rocket_customer_data`, it uses the cached data. Else, it sends a request to the API endpoint, and caches the returned JSON data for a day in the transient.
If an error occurs (`WP_Error`, or response code not `200`), the method returns false.

Closes #3143 User Client class to manage data collection from user endpoint

---

inc/Engine/License/API/Pricing.php
inc/Engine/License/ServiceProvider.php
tests/Fixtures/inc/Engine/License/API/Pricing/GetRegularSingleToInfinitePrice.php
tests/Fixtures/inc/Engine/License/API/Pricing/getInfinitePricing.php
tests/Fixtures/inc/Engine/License/API/Pricing/getPlusPricing.php
tests/Fixtures/inc/Engine/License/API/Pricing/getPlusToInfinitePrice.php
tests/Fixtures/inc/Engine/License/API/Pricing/getPromoData.php
tests/Fixtures/inc/Engine/License/API/Pricing/getPromoEnd.php
tests/Fixtures/inc/Engine/License/API/Pricing/getRegularPlusToInfinitePrice.php
tests/Fixtures/inc/Engine/License/API/Pricing/getRegularSingleToPlusPrice.php
tests/Fixtures/inc/Engine/License/API/Pricing/getRenewalsData.php
tests/Fixtures/inc/Engine/License/API/Pricing/getSinglePricing.php
tests/Fixtures/inc/Engine/License/API/Pricing/getSingleToInfinitePrice.php
tests/Fixtures/inc/Engine/License/API/Pricing/getSingleToPlusPrice.php
tests/Fixtures/inc/Engine/License/API/Pricing/isPromoActive.php
tests/Unit/inc/Engine/License/API/Pricing/getInfinitePricing.php
tests/Unit/inc/Engine/License/API/Pricing/getPlusPricing.php
tests/Unit/inc/Engine/License/API/Pricing/getPlusToInfinitePrice.php
tests/Unit/inc/Engine/License/API/Pricing/getPromoData.php
tests/Unit/inc/Engine/License/API/Pricing/getPromoEnd.php
tests/Unit/inc/Engine/License/API/Pricing/getRegularPlusToInfinitePrice.php
tests/Unit/inc/Engine/License/API/Pricing/getRegularSingleToInfinitePrice.php
tests/Unit/inc/Engine/License/API/Pricing/getRegularSingleToPlusPrice.php
tests/Unit/inc/Engine/License/API/Pricing/getRenewalsData.php
tests/Unit/inc/Engine/License/API/Pricing/getSinglePricing.php
tests/Unit/inc/Engine/License/API/Pricing/getSingleToInfinitePrice.php
tests/Unit/inc/Engine/License/API/Pricing/getSingleToPlusPrice.php
tests/Unit/inc/Engine/License/API/Pricing/isPromoActive.php

Closes #3150 
The pricing class provides ready to use methods to get specific pricing values from the pricing API.
- `get_single_pricing()`: Gets the single license pricing data
- `get_plus_pricing()`: Gets the plus license pricing data
- `get_infinite_pricing()`: Gets the inifinite license pricing data
- `get_renewals_data()`: Gets the renewals data
- `get_promo_data()`: Gets the promotion data
- `is_promo_active()`: Checks if a promotion is currently active
- `get_promo_end()`: Gets the promotion end timestamp
- `get_regular_single_to_plus_price()`: Gets the regular single to plus upgrade price
- `get_single_to_plus_price()`: Gets the current single to plus upgrade price. Different if a promotion is active
- `get_regular_single_to_infinite_price()`: Gets the regular single to infinite …

Closes #3150 Pricing class to manage pricing data usage

---

inc/Engine/Admin/Settings/Subscriber.php
inc/Engine/License/ServiceProvider.php
inc/Engine/License/Subscriber.php
inc/Engine/License/Upgrade.php
inc/Engine/License/views/upgrade-popin.php
inc/Plugin.php
tests/Fixtures/inc/Engine/License/Subscriber/displayUpgradePopin.php
tests/Fixtures/inc/Engine/License/Subscriber/displayUpgradeSection.php
tests/Fixtures/inc/Engine/License/Upgrade/displayUpgradePopin.php
tests/Integration/inc/Engine/License/API/PricingClient/getPricingData.php
tests/Integration/inc/Engine/License/Subscriber/displayUpgradePopin.php
tests/Integration/inc/Engine/License/Subscriber/displayUpgradeSection.php
tests/Unit/inc/Engine/License/Upgrade/displayUpgradePopin.php
tests/Unit/inc/Engine/License/Upgrade/displayUpgradeSection.php
views/settings/page-sections/dashboard.php

Closes #3154 
Load and instantiate the license subscriber.
- `display_upgrade_section()`: Displays the upgrade section in the license info block. Hooked on `rocket_dashboard_license_info` which is a new action
- `display_upgrade_popin()`: Displays the upgrade popin. Hooked on `rocket_settings_page_footer`

Closes #3154 Subscriber class for the upgrade events

---

inc/Engine/Optimization/Minify/JS/Combine.php

- Excluding 5 scripts related to Cache dir size issues:
https://secure.helpscout.net/conversation/1284375275/195431?folderId=2683093
https://secure.helpscout.net/conversation/1292295543/197509?folderId=2683093
```
'et_core_api_spam_recaptcha',
'cnArgs',
'__CF$cv$params',
'trustbox_settings',
'aepro',
```
- Excluding one script related to Justuno Compatibility:
`'cdn.jst.ai'`
ticket from Lucy: https://secure.helpscout.net/conversation/1293553549/197832?folderId=2683093
- cache dir size related inline JS exclusion: 
`w2dc_fields_in_categories`
coming from Web 2.0 Directory plugin
Ticket:  https://secure.helpscout.net/conversation/1282752535/194994/

Alfonso exclude inlinejs

---

inc/Engine/Optimization/Minify/JS/AbstractJSOptimization.php

Exclude external script from Minify and Combine JS per Lucy's ticket here:
File exclusion: loader.knack.com
https://secure.helpscout.net/conversation/1293470917/197816?folderId=2683093

Exclude loaded.knack.com from JS optimizations

---

inc/Engine/Optimization/DelayJS/Subscriber.php
inc/Engine/Preload/Links/Subscriber.php

Fixes #3125 
Use a private property `is_enqueued` to check if the method has already been called once, in the delay JS and preload links subscribers.
- The inline JS scripts from delay JS and preload links are not inserted multiple times if `wp_enqueue_scripts` is called more than once

Prevent duplicate addition of inline JS on multiple wp_enqueue_script calls

---

inc/Engine/Optimization/Minify/CSS/Combine.php
inc/Engine/Optimization/Minify/CSS/Minify.php
inc/Engine/Optimization/Minify/JS/Combine.php
inc/Engine/Optimization/Minify/JS/Minify.php

Proposing a fix for [#3133](https://github.com/wp-media/wp-rocket/issues/3133). 
**Combine CSS/JS increase cache/min size when versioning contains variable strings/timestamps**
Applying Remy's proposed fix here: [#3133 (comment)](https://github.com/wp-media/wp-rocket/issues/3133#issuecomment-703837954)
The fix is applied in the minify CSS and JS files, and also in the Combine CSS and JS files
- An URL using a query string version number randomly generated (or with the current timestamp) should not create duplicate combine/minify files

Fix #3133 combine css/js increase cache/min size when versioning contains variable strings/timestamps

---

inc/functions/formatting.php

Fixes #3178
- assets URLs containing spaces or other encoded characters are correctly minified/combined

Fixes #3178 Correctly minify/combine CSS/JS when the URL contains encoded characters

---

inc/3rd-party/themes/avada.php

Proposing a fix for [#3209](https://github.com/wp-media/wp-rocket/issues/3209)
(thank you @engahmeds3ed for the help!)
starting from Avada 7.2 version the `lazy_load` value is never empty, it’d be one of:
- none
- wordpress
- avada
Added verifications for the "none" value to deactivate and disable our LazyLoad option, while keeping the "empty" value verification for backward compatibility

Fix #3209 avada lazyload is detected as always active

---

inc/classes/subscriber/Plugin/class-updater-subscriber.php

Closes #3243 
Disable auto-updates for WP Rocket, as discussed in the related issue.
- `Auto-updates disabled` should be displayed in the automatic updates column, when the row is for WP Rocket.

Closes #3243 Disable auto-updates for WP Rocket

---

inc/Engine/Optimization/Minify/JS/Combine.php

Related ticket: https://secure.helpscout.net/conversation/1123723037/154713/

Add new inline JS exclusion from combine JS

---

inc/Engine/Optimization/Minify/JS/Combine.php
tests/Fixtures/inc/Engine/License/API/UserClient/getUserData.php
tests/Integration/inc/Engine/Preload/Sitemap/runPreload.php

Sitemap integration tests are failing since smashingcoding.com was wiped.
Skip the related tests, to allow the builds to pass again, while keeping the tests in place for the future.

Skip sitemap tests after smashingcoding.com unavailability

---

inc/3rd-party/hosting/pagely.php

This relates to the following two issues:
https://github.com/wp-media/wp-rocket/issues/2664
https://github.com/wp-media/wp-rocket/issues/1759
There is a hook for pagely_cache_purge_after to run a rocket_clean_domain.  Then on rocket_clean_domain there is a hook for after_rocket_clean_domain to run a pagely cache purge.  This causes a loop where it just keeps purging and purging until a timeout happens.  
This pull simply adds a global variable which is set when either hook is called that stops the purge from continuing beyond a single cycle.

Stop the infinite loop when purging cache on Pagely

---

inc/functions/formatting.php
tests/Unit/inc/functions/rocketValidateCss.php

Fixes #3232
Sanitization on exclude from combination fields prevents from excluding certain scripts.
Applied changes: 
- returning `true` if the file is internal at [rocket_is_internal_file](https://github.com/wp-media/wp-rocket/blob/a1f95920f4e1504af6826a75d1e16294e9b133eb/inc/functions/formatting.php#L135). Props to @vmanthos on this one.
- replacing `sanitize_text_field()` by `esc_url_raw()` at  [rocket_validate_css()](https://github.com/wp-media/wp-rocket/blob/a1f95920f4e1504af6826a75d1e16294e9b133eb/inc/functions/formatting.php#L113-L118) and [rocket_validate_js()](https://github.com/wp-media/wp-rocket/blob/a1f95920f4e1504af6826a75d1e16294e9b133eb/inc/functions/formatting.php#L102)
- Exclusion of URLs containing encoded spaces `%20` is working correctly

Fixes #3232 Update sanitize for CSS/JS exclusion fields

---

inc/Engine/Support/Rest.php
tests/Fixtures/inc/Engine/Support/Rest/getSupportData.php
tests/Fixtures/inc/Engine/Support/Subscriber/registerSupportRoute.php
tests/Integration/inc/Engine/Support/Subscriber/registerSupportRoute.php
tests/Unit/inc/Engine/Support/Rest/getSupportData.php

The referer check is too unreliable to be used there. We already use the consumer key and email to validate the request, and no sensitive data are sent back, so it's an acceptable trade-off to remove it.

Remove referer check from support REST endpoint

---

inc/ThirdParty/Plugins/Ecommerce/WooCommerceSubscriber.php

**Related ticket:** https://secure.helpscout.net/conversation/1335093437/210973?folderId=273766
It's for the following plugin: [WooCommerce Additional Variation Images](https://woocommerce.com/products/woocommerce-additional-variation-images/)

Add nonce action for WooCommerce Additional Variation Images

---

inc/Engine/Admin/Beacon/Beacon.php
inc/Engine/Admin/Settings/Page.php
inc/Engine/Optimization/DeferJS/DeferJS.php
tests/Fixtures/inc/Engine/Optimization/DeferJS/AdminSubscriber/excludeJqueryDefer.php
tests/Fixtures/inc/Engine/Optimization/DeferJS/DeferJS/excludeJqueryCombine.php
tests/Fixtures/inc/Engine/Optimization/DeferJS/DeferJS/excludeJqueryUpgrade.php
tests/Fixtures/inc/Engine/Optimization/DeferJS/Subscriber/excludeJqueryCombine.php
wp-rocket.php

The previous pattern could be matching unexpected files.
This new pattern has been tested against the jQuery URLs we were previously excluding, and also some of the unexpected URLs that were matching. See https://regex101.com/r/nQMi70/3

Update the pattern used for jQuery exclusion from defer

---

.github/workflows/test_wprocket.yml
.github/workflows/test_wprocket_legacy.yml

Fix the WP version in our automated tests to correctly use the version defined in the configuration

Fix wp version tests

---

inc/Dependencies/RocketLazyload/Image.php

Fixes #3056
Change already reviewed and QA'ed on https://github.com/wp-media/rocket-lazyload-common/pull/90

Fixes #3056 Prevent PHP notice when picture element doesn't contain any source element
